엔티티 생성
E-TF/Momo pull request #18
Opened 2022-01-27 11:44 UTC by myj4513

#17

2022-01-27 14:36 UTC, yyy9942 requested changes
JPA를 씀에 있어서 어떤게 어떻게 동작하는지는 알고 작성해야 합니다. 그렇지 않을시 쿼리나 데이터가 원하지 않는 방향으로 흐를 수 있어요.

1. GenerateValue의 동작 방식. Auto는 기본값이라서 안적어도되고, 다른거 쓸거면 명시해야합니다.
2. `@Column`에 name을 안줘도 됩니다. 디폴트로 카멜케이스 변수명과 스테이크케이스의 테이블 컬럼명을 연결해줘요.
3. BaseEntity에 공통 컬럼을 설정했으면 그 외 확장하는 엔티티에서는 그걸 중복해서 선언하면 안됩니다.
4. 엔티티에 컬럼 길이와 같은 중요한 밸리데이션이 있다면 hibernate validation을 사용해주세요
5. 테스트코드 작성 시도 좋습니다!

2022-01-27 14:36 UTC, yyy9942 commented on src/main/java/com/project/momo/entity/MemberPointsHistory.java
> +    private LocalDateTime createdAt;
`Base Entity`에 `createdAt`이 있다면 여기는 이걸 만들어줄 필요가 없지 않을까요?

2022-01-27 14:36 UTC, yyy9942 commented on src/main/java/com/project/momo/repository/MemberRepository.java
> +public class MemberRepository {
JpaRepository를 구현하는 인터페이스로 생성하면 엔티티메니저를 직접 다루지 않아도 됩니다. save, delete등등의 메서드가 자동으로 사용할 수 있게됩니다.

2022-01-27 14:36 UTC, yyy9942 commented on src/main/java/com/project/momo/repository/MemberRepository.java
> +    public Member findOne(Long id) {
findOne이라는 이름의 메서드는 Spring Boot 1버전대의 JpaRepository에 있던 메서드 네이밍입니다. Spring boot 2.0부터는 findById라는 네이밍으로 변경되었으며 Optional을 리턴하도록 바뀌었어요. DB에 있는 데이터는 있을수도있고 없을수도 있습니다. null에 안전한 프로그램을 만들려면 Optional을 사용하는것을 연습해보세요.

추가적으로 이것 또한 JpaRepository를 구현하면 없어도 되는 메서드입니다.

2022-01-27 14:36 UTC, yyy9942 commented on src/main/java/com/project/momo/repository/PaymentRepository.java
> +    }
이렇게 엔티티매니저를 사용하게 되면 동일한 메서드를 계속해서 구현해야합니다. JpaRepository 사용을 검토해보세요.

2022-01-27 14:36 UTC, yyy9942 commented on src/main/resources/application.yml
> +    password: 111111
데이터베이스 주소와 username, password는 깃헙같은 공개된 공간에 게시하면 안됩니다.
깃헙을 도는 크롤링봇이 이를 스크래핑해가서 해킹해가는 사례가 생길 수 있으니, 이런 데이터는 별도의 파일로 만들어서 push하지 않는 방법을 쓰거나 환경변수를 활용해주어야 해요.

2022-01-27 14:36 UTC, yyy9942 commented on src/main/resources/application.yml
> +      ddl-auto: create
ddl-auto는 DDL을 어플리케이션레벨에서 실행하도록 만듭니다.
DDL의 경우 어플리케이션에서 날아가는것이 아니라, 개발자가 직접 생성해주는편이 데이터 안정성이나 테이블생성에 더 안정적입니다.
create를 제거하고 validate와 같은 DDL을 사용하지 않는 레벨로 내려주세요.

2022-01-27 14:36 UTC, yyy9942 commented on src/test/java/com/project/momo/repository/MemberRepositoryTest.java
> +    }
최초의 Assert를 쓰는 테스트네요! 굳굳

2022-01-27 14:36 UTC, yyy9942 commented on src/test/java/com/project/momo/repository/PaymentRepositoryTest.java
> +    }
Rollback 을 false로 지정해둔 이유가 있나요?

2022-01-27 15:09 UTC, yyy9942 commented
PR을 날릴 때에는 이 코드가 어떤 작업을 위한 코드인지, 어떻게 작성하였는지를 리뷰어에게 설명해주어야 합니다. 
코드에 대한 설명과 논의하고싶은 부분을 명확하게 짚어주어야 리뷰어도 집중적으로 리뷰할 곳을 찾을 수 있으며, 코드를 상세히 이해하여 리뷰할 수 있게 됩니다.

이를 위해 Pull Reuest Template를 사용하는것도 고려해볼 수 있겠습니다.

Pull Request에 대한 감은 이 링크를 참고해주세요.
https://2jinishappy.tistory.com/337

2022-01-27 15:44 UTC, jinyoungchoi95 approved these changes
안녕하세요 :)
간단하게 리뷰가 재미있어 보여 리뷰했습니다 ㅎㅎ

대부분 리뷰한 내용들이 다른 코드에도 적용되는 부분이 많아 공통된 코드의 문제를 처음볼때만 리뷰를 달았어요. 나머지 코드도 동일한 이슈가 있는 부분이 많으니 참고해주세요

그리고 제 의견을 이야기하자면 클래스에서 기본생성자는 항상 명시해주어야한다고 생각해요. jpa의 entity기본 스펙은 기본생성자(public or protected)가 기본 스팩이잖아요? 개발을 하다보면 다른 생성자도 만들게 될 텐데 지금 명시하지 않아도 되는 이유는 자바 컴파일러가 다른 생성자가 없어서 대신 생성해주기 때문이에요. 개인적으로는 상황에 따라 대신 생성해주는 것에 대해서는 막고 명시적으로 생성해두어야한다고 생각합니다.
기본생성자를 명시했을 때 protected와 public 중 무엇을 고려해가면서 사용하면 좋을지 생각해보는 것도 좋은 기회가 될 것 같네요 ㅎㅎ

다음이 언제가 될지는 모르니 제껀 approve해둘게요 🙆‍♂️

2022-01-27 15:44 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/entity/AdjustPoint.java
> +public class AdjustPoint extends BaseEntity{
```suggestion
public class AdjustPoint extends BaseEntity {
```
찾아라 컨벤션! 👀 
항상 다른사람과의 협업 가독성을 위해서 코드 컨밴션은 지켜주세요.
인텔리 제이 내에서 window:`ctrl + alt + l`, mac:`opt + cmd + l`

2022-01-27 15:44 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/entity/AdjustPoint.java
> +    @ManyToOne
`@ManyToOne`은 기본 fetch type이 EAGER입니다.
EAGER로 두신 이유가 따로 있을까요? EAGER로 fetch type을 설정한 경우에 문제가 무엇이 있을까요?

2022-01-27 15:44 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/entity/Article.java
> +    private LocalDateTime writtenAt;
BaseEntity에 동일한 의미를 담은 createdAt이 있는데 이 클래스 변수가 존재하는 이유가 따로 있을까요?

2022-01-27 15:44 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/entity/CodeGroup.java
> +    private List<Code> codes = new ArrayList<>();
`@OneToMany`를 사용하시는 이유가 따로 있을까요?

2022-01-27 15:44 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/entity/Gathering.java
> +    private int max_number;
```suggestion
    private int maxNumber;
```
자바 네이밍의 기본 컨벤션은 카멜 케이스입니다 :)

2022-01-27 15:44 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/entity/MemberPointsHistory.java
> +    private Long id;
여기는 id generate strategy가 안걸려있네요 :)

2022-01-27 15:44 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/entity/BaseEntity.java
> +    private String createdBy;
2개를 동시에 두는 이유가 따로 있을까요?

2022-01-27 15:48 UTC, yyy9942 commented on src/main/java/com/project/momo/entity/CodeGroup.java
> +    private List<Code> codes = new ArrayList<>();
이부분은 저도 못보고있었네요. OneToMany 뿐만 아니라 ` new ArrayList<>();`또한 필요하지 않은 코드입니다. 최초 엔티티를 new로 생성할 때에는 당연히 null이지만, 이후 엔티티매니저에 의해 조회할 경우 초기화된 list가 존재하게 됩니다.

2022-01-28 06:03 UTC, myj4513 commented on src/main/java/com/project/momo/entity/AdjustPoint.java
> +    private Long id;
`use-new-id-generator-mappings: true` 를 사용하면 대체키를 생성하여 기본키로 설정하게 됩니다. 이때 `@GeneratedValue`에 `strategy` 속성을 주지 않는 경우, 디폴트로 `GenerationType.AUTO`가 적용되게 되는데 AUTO는 DB별로 Sequence를 지원하는 여부에 따라 TABLE 전략과 SEQUENCE 전략을 사용하게 됩니다. MYSQL의 경우 TABLE 전략을 사용합니다.

IDENTITY 전략의 경우 DB에 데이터를 저장한 후에 기본키를 조회해 오는 방식을 사용하기 때문에 엔티티를 영속화 시킬 때 쓰기지연 기능을 사용하지 못하며, `allocationSize`를 통한 성능 개선을 할 수 없게 됩니다.

2022-01-28 06:05 UTC, myj4513 commented on src/main/java/com/project/momo/entity/AdjustPoint.java
> +    private LocalDateTime adjustAt;
`auto-ddl: create`을 사용하여 스키마가 자동생성 되었을 때 datetime(6)이 적용되어서 미처 몰랐습니다.
수정하겠습니다.

2022-01-28 06:07 UTC, myj4513 commented on src/main/java/com/project/momo/entity/MemberPointsHistory.java
> +    private LocalDateTime createdAt;
아.. 실수로 들어간 것 같습니다.
코드 검토 제대로 하겠습니다 ㅜㅜ

2022-01-28 06:09 UTC, myj4513 commented on src/main/resources/application.yml
> +      ddl-auto: create
`validate` 레벨을 사용하여 엔티티와 테이블 정상 매핑 확인용으로 사용하겠습니다.

2022-01-28 06:12 UTC, myj4513 commented on src/main/java/com/project/momo/entity/AdjustPoint.java
> +public class AdjustPoint extends BaseEntity{
리뷰 감사합니다!!
미처 생각을 못했었는데 가독성에 영향을 줄 수 있겠네요.
컨벤션 지키며 작성하겠습니다!!.😀

2022-01-28 06:19 UTC, myj4513 commented on src/main/java/com/project/momo/entity/BaseEntity.java
> +    private String createdBy;
자바가 다중상속을 지원하지 않기 때문에 하나의 클래스에 모아 작성을 했습니다.
혹시 저 속성들을 분리하며 유연하게 공통컬럼을 적용하게 하는 방법이 있을까요??

(저도 계속 생각해보겠습니다!)

2022-01-28 06:38 UTC, myj4513 commented on src/main/java/com/project/momo/entity/CodeGroup.java
> +    private List<Code> codes = new ArrayList<>();
다시 확인해보니 `CodeGroup`과 `Codes` 간에 불필요한 양방향 연관관계가 생성되네요.
해당 코드를 삭제하여 `Codes`에서 `CodeGroup`으로 단방향 연관관계만 유지하겠습니다.

엔티티매니저에 의한 List 초기화 시에는 다음과 같은 문제가 발생할 것 같습니다.
만약 두 엔티티 간에 양방향 연관관계가 존재한다고 가정할 때
```
CodeGroup codeGroup = new CodeGroup();
em.persist(codeGroup);

Codes code = new Code();
code.setCodeGroup(codeGroup);
codeGroup.getCodes().add(code);  //이부분
em.persist(code);
```
위와 같은 코드를 작성하는 경우에는 NullPointerException이 발생하지 않나요??

2022-01-28 06:50 UTC, myj4513 commented on src/main/java/com/project/momo/entity/AdjustPoint.java
> +    @ManyToOne
아뇨.. JPA에 대한 이해가 부족했습니다
fetchType을 EAGER로 사용하면 연관 관계의 객체들을 모두 즉시 조회하는 N + 1 문제가 발생하게 됩니다.
(fetchType = LAZY) 로 적용하겠습니다.

2022-01-28 09:42 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/entity/BaseEntity.java
> +    private String createdBy;
말을 조금 잘못 전달한 것 같네요. BaseEntity에 createdBy 변수가 굳이 필요한가에 대한 이야기였어요.

상속을 위한 BaseEntity는 재사용을 사용하는데 있어서 좋은 수단이 될 수 있지만 그만큼 상속이 가능하지 않은 정보에 대해서 상속을하게되면 문제가 발생해요. 가령 모든 Entity에 대해서 createdAt이라는 생성시간 필드는 존재하지만 누구에게 생성되었다는 createdBy는 모든 entity에서 사용하는 정보인가요? erd만 보면 그런게 보이지 않는 테이블이 몇개가 보여요.

상속은 클래스에 대한 정보가 순수한 is-a의 관계일 때만 사용을 고려해야하며 이런 부분이 고려되지 않는다면 사용을 지양하는것이 좋아요.

2022-01-28 10:05 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/entity/AdjustPoint.java
> +    @ManyToOne
@myj4513 조금 더 구체적으로 이야기하자면 단순히 즉시 조회한다고 N+1 문제가 발생한다는건 조금 잘못된 표현이에요.
EntityManager에서 제공하는 findById는 EAGER로 즉시로딩을해도 N+1이 발생하지는 않거든요.

다만 저희가 앞으로 사용해야할 무수한 data jpa의 쿼리 메소드를 비롯한 모든 jpql 구문때문에 즉시로딩에서 N+1이 발생해요.  jpql의 경우 즉시로딩이 우선되는 것이 아닌, 쿼리가 우선 날아가고 이후에 즉시로딩을 확인하거든요.

즉,
> 쿼리 메소드 > jpql 변환 > jpql을 그대로 쿼리 생성 후 전송(1쿼리) > 즉시로딩 걸린 프록시에 대해서 다시 조회(N쿼리)

로 발생하는 것과 같은 예시가 일반적인 N+1이 즉시로딩에서 발생하는 케이스인거죠.

2022-01-28 10:11 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/entity/CodeGroup.java
> +    private List<Code> codes = new ArrayList<>();
@myj4513 mappedBy 주인관계를 조금 더 알아보는 것이 좋을 것 같아요.

mappedBy로 인해서 Code가 주인이 되는 관계구조에서 과연 `codeGroup.getCodes().add(code);`를 하는 이유가 있을까요? 주인이 아닌 entity에 저장을 해서 사용을 하는 상황이 과연 좋은 상황인지에 대해서 의문이 드네요.
사용하지 않는 상황에 대한 케이스를 생각하는 것은 필요한 개발 외의 개발에 시간을 소비하게 해요.

2022-01-31 14:01 UTC, yyy9942 requested changes
고생하셨어요~

2022-01-31 14:01 UTC, yyy9942 commented on src/test/java/com/project/momo/repository/PaymentRepositoryTest.java
> +        Assertions.assertThat(payments.size()).isEqualTo(1);
이 테스트는 추후 깨질 가능성이 높습니다. 데이터베이스에 데이터가 하나라도 들어있는 상태라면 findAll을 했을 때 지금 저장한 데이터 + 이미 있는 데이터로 인해 데이터 개수가 달라질 것이고 테스트가 깨질 것입니다.

2022-02-01 04:24 UTC, myj4513 commented on src/main/java/com/project/momo/entity/AdjustPoint.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
객체를 생성할 때 기본생성자가 아닌 정적 팩토리(public)를 사용하여 이름을 부여하여 코드의 역할을 명시하고 필드 접근을 제한하고자 하였습니다. 

JPA는 DB가 엔티티 객체에 값을 주입할 때 Reflection API와 기본생성자를 사용합니다. Reflection은 로드된 클래스 정보를 사용해 접근제한자에 상관 없이 필드, 메서드, 생성자에 접근할 수 있습니다. 
그러나 지연로딩의 경우 JPA는 실제 객체가 아닌 프록시를 생성하는데 이때 상속을 사용하기 때문에 기본생성자의 접근제한자를 protected로 설정하였습니다.

2022-02-01 04:27 UTC, yyy9942 commented on src/main/java/com/project/momo/entity/AdjustPoint.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
이 엔티티로 단위 테스트코드를 짜야한다면 문제가 없을까요?

2022-02-01 06:35 UTC, myj4513 commented on src/main/java/com/project/momo/entity/AdjustPoint.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
테스트 코드의 경우는 생각해보지 못했네요..

한가지 궁금한 점이 있습니다!!🧐
테스트 코드의 중요성은 이해하고 있지만, 테스트 코드를 위해 production code가 변경되는 것 또한 문제가 될수 있다고 생각하는데, 이건 효율적이고 정확한 테스트를 위해 포기해야 하는 부분인가요?

2022-02-02 05:14 UTC, myj4513 commented on src/main/java/com/project/momo/entity/ChargePoints.java
>      private int amount;
앗! 중복된 validation이었네요. 
points 값을 다루는 amount 컬럼도 int는 부족하니 long까지 확장하는게 맞는것 같습니다.
리뷰 감사합니다!

2022-02-02 05:15 UTC, myj4513 commented on src/main/java/com/project/momo/entity/Chat.java
>      private String content;
넵 이것도 확장하겠습니다😀

2022-02-02 05:22 UTC, myj4513 commented on src/main/java/com/project/momo/entity/Club.java
>      private Code code;
`Code`는 `CodeGroup` 값에 따라 애플리케이션에 공통으로 사용되는 데이터를 저장하는 역할을 합니다.
주로 각 기능들의 카테고리 역할을 수행합니다.

몇가지 예시를 들면,
`CodeGroup.name = "ArticleCateogry"` 인 경우,

`Code.codeKey = "NOTICE"`
`Code.name = "공지사항"`

`Code.codeKey = "REVIEW"`
`Code.name = "모임후기"` 등의 데이터가 들어갑니다.

2022-02-02 05:25 UTC, myj4513 commented on src/main/java/com/project/momo/entity/BaseEntity.java
> +    protected String createdBy;
넵 밑에 리뷰에서 말씀하신 것처럼 어떤 데이터가 들어갈지 고려하여 룰을 정해보겠습니다!

2022-02-02 05:34 UTC, myj4513 commented
## Key Changes
- 기본 타입(int, long) @NotNull 제거
- MEMBER.login_id, CLUB.name unique 제약조건 추가
- 결제 및 포인트 관련 type 변경(엔티티:int -> long, DB:int -> bigint)
- 채팅 및 댓글 comment 컬럼 확장(varchar(255 -> 1000)
- created_by 크기 확장varchar(20->45)
- ADJUST_POINTS member_id 오타 수정
- 불필요 CRUD TEST삭제

2022-02-02 07:05 UTC, yyy9942 commented on src/main/java/com/project/momo/entity/Club.java
>      private Code code;
대부분의 엔티티에 Code가 있던데요 조금 이상한거같네요.
단순히 엔티티에 변수명으로 code가 있는데 이게 어떤 코드로 데이터가 들어갔는지도 알기 어렵고, 예시로 들어준 공지사항이나 모임 후기 등은 엔티티에 1:1 관계로 코드가 들어가는 구조가 아니라 게시판의 Category등으로 들어가야겠죠? 예를들어 Board에 변수명으로 code가 있다면 이게 무슨 코드인지, 어떤 데이터인지 알 수 없을 것입니다. 변수명이 category라면 이게 카테고리이고 공통 코드로 작동한다는걸 알 수 있겠지요. 사실 이 경우에도 공통코드보다는 Enum을 쓰는게 더 깔끔하긴 합니다.

정확히 어떤 데이터가 들어갈지 명시해주시고 변수명을 바꿔보는건 어떤가요?

2022-02-02 07:20 UTC, yyy9942 commented on src/main/java/com/project/momo/entity/Payment.java
> +        payment.createdBy = member.getCreatedBy();
멤버의 아이디를 createdBy로 넣어줄 것이라면 명시적으로 `loginId`를 가져와서 넣어주는게 더 좋아보이네요.

2022-02-02 07:20 UTC, yyy9942 commented on src/main/java/com/project/momo/entity/AdjustPoint.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
테스트를 위해 프로덕션코드를 바꿔야 하는 상황이 오는게 베스트는 아닙니다. 다만 코드를 짤 때 테스트가 용이하게 구조적으로 설계하고 작성하는게 더 좋죠

2022-02-02 07:21 UTC, yyy9942 commented
@myj4513 
공통코드부분과 createdBy부분만 개선되면 이 PR도 끝날 수 있겠군요

2022-02-03 05:16 UTC, yyy9942 approved these changes
고생하셨어요~ 머지하셔도 좋습니다.

2022-02-03 05:16 UTC, yyy9942 commented on src/main/java/com/project/momo/entity/ClubPointsHistory.java
> +    private String category;
지금은 String으로 해두었지만, 추후 Enum을 생성할 경우 이 파라미터의 타입도 Enum으로 바꿔주어야합니다.

2022-02-03 06:05 UTC, merged