(Spring Security/JWT ) 인증/인가 구현
E-TF/Momo pull request #20
Opened 2022-02-10 13:27 UTC by myj4513

## What is this Pull Request about?
- SpringSecurity와 JsonWebToken을 사용하여 인증/인가를 구현하였습니다.
- 스프링 시큐리티의 라이브러리들을 최대한 활용하고자 커스텀 필터의 구현을 최소화하고 기존 흐름을 따르고자 하였습니다.
- 애플리케이션에 별도의 권한이 존재하지 않기 때문에 AccessDeniedException이 발생하지 않으므로 AccessDeniedHandler를 구현하지 않았습니다.
- Refresh Token을 구현하지 않고 JwtFilter에서 토큰에 대한 유효성 검증을 통과했을 때, TokenProvider.refreshToken()을 사용하여 새로운 토큰을 발급하여 로그인을 유지하도록 설계하였습니다.

<br>

## Key Changes
- Security Flow Chart
<img width="573" alt="SecurityFlowChart" src="https://user-images.githubusercontent.com/78058268/153413056-0dae92c4-9637-4fed-89e3-3b40d33b823f.png">

- 토큰 구성

![image](https://user-images.githubusercontent.com/78058268/153413422-938ff60c-da7b-40ad-9588-67e540369065.png)
- 애플리케이션에 별도의 권한이 존재하지 않기 때문에 authentication의 authorities에는 빈 리스트를 넣어주었습니다.
- Authentication 구성(UsernamePasswordAuthenticationToken)
  - principal -> Long memberId
  - credential -> null
  - authorities -> Collection.emptyList()
<br>

## To Reviewers
- 스프링 시큐리티와 JWT를 공부하며 처음 적용해 보았는데, 생각보다(?) 너무 재미있었습니다.😋😋
- 시큐리티 필터의 흐름에 대한 집중적인 리뷰 부탁드립니다.(다양한 코드를 보며 공부해보았는데 확신이 부족합니다)
- 테스트 코드는 완성하는 대로 업데이트하겠습니다.(이 부분도 공부가 필요합니다..)
- PR 자체에 대한 리뷰도 부탁드립니다!!
- 비판적인 리뷰도 언제나 환영입니다!!😆

2022-02-12 10:08 UTC, Lob-dev commented on src/main/java/com/project/momo/utils/ResponseManager.java
> +    private static final String AUTHORIZATION_HEADER = "Authorization";
상수로 정의하신 값들이 정의된 Enum이 존재하는 것으로 알고 있는데요~ 그런 것을 활용하시는 것은 어떨까요?

ref. org.springframework.http.HttpHeaders, java.nio.charset.StandardCharsets 등

2022-02-12 10:16 UTC, Lob-dev commented on src/main/java/com/project/momo/security/userdetails/UserDetailsServiceImpl.java
> +    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
이 로직에서 NullPointerException이 발생하는 경우가 있을까요? 한번 생각 해보시는 게 좋을 것 같습니다!

2022-02-12 10:42 UTC, yyy9942 requested changes
코드가 점점 깔끔해지고, 완성도가 높아지는게 보입니다. 앞으로도 이렇게만 진행해주세요.

1. 요청시마다 새로운 토큰을 발급한다면 이론상 하나의 토큰으로 무한히 로그인이 가능합니다. 보안적으로 큰 이슈가 될거에요. 정석적으로 access token/refresh token을 사용하는걸 고려해보세요.
2. Json 라이브러리는 JsonObject/ObjectMapper 중 하나로 통일해주세요. 기본적으로 스프링에서 사용하는 ObjectMapper를 사용하는것이 좀 더 권장할만 하겠네요.

2022-02-12 10:42 UTC, yyy9942 commented on src/main/java/com/project/momo/exception/GlobalExceptionHandler.java
> +    }
꽤 독특한 방식으로 Validation Error를 세팅하고 있네요. ResponseManager 유틸을 새로 만드신것도 옛날 서블릿시절의 에러처리를 보는듯합니다 ㅎㅎ

2022-02-12 10:42 UTC, yyy9942 commented on src/main/java/com/project/momo/security/filter/JwtFilter.java
> +    }
이렇게 진행할 경우 토큰이 한번 유출되면 계속해서 토큰을 갱신하며 토큰의 유효기간이 사실상 없어지는 이슈가 생깁니다. 토큰의 탈취는 언제든지 발생할 수 있기 때문에 토큰을 무효화시킬 수 있는 방법이 필요합니다.
기본적으로 한번 발급한 토큰은 반드시 유효기간이 필요하며, 필요할 경우 일정기간 갱신하되 무한정 갱신하도록 만들면 안됩니다. 인증방식에 대해서는 조금 더 고민이 필요해보이네요.

2022-02-12 10:42 UTC, yyy9942 commented on src/main/java/com/project/momo/security/filter/JwtFilter.java
> +    }
리프래쉬 토큰을 주기 싫은것이라면 토큰 발급 후 유효기간이 지나면 갱신 없이 그냥 재로그인하도록 처리해도 됩니다. 이런 방식으로 하면 사용자가 사용 도중 로그아웃될시 다시 로그인을 해야하는 불편함이 생기겠지요.

2022-02-12 10:42 UTC, yyy9942 commented on src/main/java/com/project/momo/security/filter/JwtFilter.java
> +        }
찾아라 매직넘버! `bearerToken.substring(7);` 에 있는 리터럴은 별도의 상수로 뺴는게 좋습니다.

2022-02-12 10:42 UTC, yyy9942 commented on src/main/java/com/project/momo/security/userdetails/UserDetailsServiceImpl.java
> +    }
없는 유저를 찾았을 때 NPE가 발생할겁니다. 별도의 명시적인 예외처리가 필요해보여요.

2022-02-12 10:42 UTC, yyy9942 commented on src/main/java/com/project/momo/security/filter/LoginAuthenticationFilter.java
> +    private final ObjectMapper objectMapper = new ObjectMapper();
`ObjectMapper`는 Spring-web에 기본적으로 등록된 빈이라서 직접 생성해주는것 보다 주입받아 사용하는것이 재사용성을 높일 수 있습니다. 또한 Json관련해서 직렬화/역직렬화는 하나의 라이브러리로 통합하여 사용하는편이 좋습니다. 여러가지 옵션이 있는데 이게 여기저기서 다른채로 사용하게 되면 같은 객체를 직렬화하여도 다른 Json 결과값이 나올 수 있어요. `JSONObject` / `ObjectMapper` 중 하나를 정책적으로 정하는게 좋아보이네요.

2022-02-12 10:42 UTC, yyy9942 commented on src/main/java/com/project/momo/security/filter/LoginAuthenticationFilter.java
> +            UsernamePasswordAuthenticationToken auth = new UsernamePasswordAuthenticationToken(loginForm.getLoginId(), loginForm.getPassword());
`request.getReader()` 는 1회용 메서드입니다. 한번 사용할 시 Request에 있는 파라미터가 모두 소모되며 다시 조회할 수 없게됩니다. [참고](https://hihoyeho.tistory.com/entry/getInputSream-%EB%B0%8F-getReader-%EC%82%AC%EC%9A%A9-%ED%9B%84-parameter-%EC%86%90%EC%8B%A4)
request에서 getReader를 사용하지 말고, 위 글을 참고하여 새로운 스트림으로 복사하여 사용해주세요. 해당 필터 이후에 다른 필터를 사용하지 않는다고 하여도 request에서 1회용 스트림을 소모하는 작업은 지양해야 합니다.

2022-02-12 10:42 UTC, yyy9942 commented on src/main/java/com/project/momo/security/filter/LoginAuthenticationFilter.java
> +            UsernamePasswordAuthenticationToken auth = new UsernamePasswordAuthenticationToken(loginForm.getLoginId(), loginForm.getPassword());
ParameterMap이 아니라 스트림으로 뽑아오는 방법도 있습니다. 구글링해보면 쉽게 찾을 수 있으니 한번 찾아보는것도 좋겠네요.

2022-02-12 10:42 UTC, yyy9942 commented on src/main/java/com/project/momo/security/filter/LoginAuthenticationFilter.java
> +        }
에러가 났는데 로그만찍은채로 넘어간다면 추후 에러 핸들링에 어려움이 있지 않을까요?

2022-02-12 10:42 UTC, yyy9942 commented on src/main/java/com/project/momo/security/handler/AuthenticationEntryPointImpl.java
> +        }
누가/어떤 방식으로 접근했는지가 로그에 찍히지 않는듯합니다. 에러 핸들링시 로그를 보고 진행해야하는데 위 정보만으로는 어렵지 않을까요?

2022-02-12 10:42 UTC, yyy9942 commented on src/main/java/com/project/momo/security/handler/AuthenticationEntryPointImpl.java
> +        }
이미 커밋된 리스폰스라면 별도의 예외를 던지는것도 하나의 방법이 될 수 있습니다.

2022-02-12 10:42 UTC, yyy9942 commented on src/main/java/com/project/momo/security/handler/LoginAuthenticationFailureHandler.java
> +    }
발생한 에러가 `InternalAuthenticationServiceException`, `BadCredentialsException` 두개 다 아니라면 메세지에는 NULL만 들어갈 것으로 보입니다. 디폴트 처리를 주어야할듯 하네요.

2022-02-12 10:42 UTC, yyy9942 commented on src/main/java/com/project/momo/security/config/SecurityConfig.java
> +    }
내부 필드로 사용중인 아래 필드에 대해서 주입을 직접적으로 해주는게 좋을거같네요. 빈 컨테이너에 들어가니 동작은 하겠지만 이후 테스트작성이나 필드 주입이 어려워보입니다.

```
    @Autowired
    TokenProvider tokenProvider;
```

2022-02-12 10:42 UTC, yyy9942 commented on src/main/java/com/project/momo/security/handler/LoginAuthenticationSuccessHandler.java
> +    TokenProvider tokenProvider;
접근제어자 설정이 필요해보이며, 위에 적어둔대로 별도의 생성자 주입으로 빼는게 좋을거같네요.

2022-02-12 10:42 UTC, yyy9942 commented on src/main/java/com/project/momo/security/jwt/TokenProvider.java
> +    }
`1000` 같은 리터럴은 별도의 상수로 관리하는게 좋습니다.

2022-02-12 10:42 UTC, yyy9942 commented on src/main/java/com/project/momo/security/jwt/TokenProvider.java
> +                .claim("memberId", userDetails.getId())
상수로 변경해야할 대상이네요 `memberId`

2022-02-12 10:42 UTC, yyy9942 commented on src/main/java/com/project/momo/security/jwt/TokenProvider.java
> +        Long memberId = Jwts.parserBuilder().setSigningKey(key).build().parseClaimsJws(jwt).getBody().get("memberId", Long.class);
여기서도 동일한 리터럴인 `memberId`를 사용중이네요. 상수로 빼서 관리하는게 재사용성 및 관리차원에서 좋을거에요.

2022-02-12 10:42 UTC, yyy9942 commented on src/main/java/com/project/momo/security/jwt/TokenProvider.java
> +            Jwts.parserBuilder().setSigningKey(key).build().parseClaimsJws(jwt);
Jwts.parserBuilder().setSigningKey(key).build() 로 만든 객체를 재사용할 수는 없을까요?

2022-02-12 10:42 UTC, yyy9942 commented on src/main/java/com/project/momo/service/SignupService.java
> +    }
회원가입 하기 전 회원이 사용하고 싶은 loginId를 체크하는 api도 필요할듯 한데요, public 하게 바꿔주는건 어떨까요?

2022-02-12 10:42 UTC, yyy9942 commented on src/main/java/com/project/momo/service/SignupService.java
> +        member.encryptPassword(passwordEncoder);
Member를 만들 때 부터 패스워드는 암호화된 상태로 만들어져야 합니다. 멤버쪽에서 암호화/복호화를 진행한다면 현재 이 객체에 들어있는 패스워드가 암호화된 패스워드인지 암호화되기 전 패스워드인지 판단하기 어려울 수 있기 때문에 도메인과 이러한 비즈니스로직은 분리가 필요합니다.

패스워드 인코딩은 별도의 레이어에서 진행하고 멤버 도메인에서는 암호화/복호화를 모르도록 처리해주세요.

2022-02-12 10:42 UTC, yyy9942 commented on src/main/java/com/project/momo/utils/ResponseManager.java
> +    private static final String APPLICATION_JSON = "application/json";
[option] 요건 제가 기억하기로는 `MediaType`에 상수가 있던거같네요.

2022-02-13 06:46 UTC, jinyoungchoi95 commented on build.gradle
> +	implementation 'org.json:json:20211205'
해당 dependency를 추가한 이유가 있을까요 ?

2022-02-13 06:46 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/controller/HomeController.java
> +    }
굳이 "main page"를 반환하는 메소드를 만든 이유가 있을까요?

2022-02-13 06:46 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/controller/SignupController.java
> +@RequestMapping("/api/signup")
`/api/signup`이 어떤 resource에 대한 가입인지 그 의도가 불명확해보이네요.
어떤 의도로 작성해주신걸까요?

2022-02-13 06:46 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/controller/SignupController.java
> +    }
`DuplicatedLoginIdException`에 대한 예외를 핸들링하셨네요 👍 

다만 한가지 고민해보아야 할 부분들이 보여요. 과연 SignupController가 가져야할 책임이 어디까지일까요?
지금 SignupController는 가입에 대한 외부 요청을 처리하는 한편, 내부 로직에서 발생하는 exception에 대한 handling까지 처리하고 있어요. 제가 보기엔 해당 클래스가 가져야할 책임이 많아보이는데 어떻게 생각하세요?

2022-02-13 06:46 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/dto/signup/SignupForm.java
> +    @NotBlank
`@Email`이 제한하는 pattern의 범위는 조금 특별한데요. 그와 동시에 `@NotBlank` `@NotNull`들도 범위들을 알아보면 신기하게 나와있어요.
그럼 여기서 문제. `@Email`과 `@NotBlank`중 " "가 입력값으로 들어왔을 때 어떤 에러로 반환을 할까요?

2022-02-13 06:46 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/security/filter/JwtFilter.java
> +    private final String AUTHORIZATION_HEADER = "Authorization";
```suggestion
    private static final String AUTHORIZATION_HEADER = "Authorization";
```
상수는 static으로 정의합니다.

또한 Springframework에서는 HttpHeaders.AUTHORIZATION와 같은 상수값을 제공합니다.
굳이 새로운 상수를 정의하기보다는 이미 제공하고 있는 상수가 있는 경우 사용하는편이 더 좋다고 생각드네요 🤔

2022-02-13 06:46 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/security/filter/JwtFilter.java
> +public class JwtFilter extends GenericFilterBean {
`GenerincFilterBean`과 `OncePerRequestFilter`의 차이가 뭘까요? 🤔

2022-02-13 06:46 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/security/filter/JwtFilter.java
> +        }
이렇게 valid된 jwt 토큰의 경우 contextholder에 저장되지 않아 차후 spring security에서 authenticationEntryPoint로 일괄 처리 하시는 것으로 보이는데요, 그럼 어떤 문제가 있을까요?

jwt를 resolving하는 과정에서 생기는 에러의 경우 물론 "잘못된 jwt"를 보낼때도 있지만, "만료된 jwt"를 보내기 때문에 다시 요청을 보내야하는 경우도 있어요. 전부  authenticationEntryPoint로 한번에 처리하면 프론트입장에서는 어떤 케이스인지에 대해서 궁금해할 수도 있지 않을까요?

2022-02-13 06:46 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/security/filter/JwtFilter.java
> +            ResponseManager.setResponseToken((HttpServletResponse) response, tokenProvider.refreshToken(authentication));
요청마다 token을 refresh하는 sliding session 작업을 하고 계시네요.
이렇게 되는 경우 "모든" 요청을 refresh해주게 되는데요, 이렇게 진행하면 장점이 무엇이고 단점이 무엇일까요?

2022-02-13 06:46 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/security/userdetails/UserDetailsImpl.java
> +@ToString
어디서 사용되고 있을까요?👀

2022-02-13 06:46 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/service/SignupService.java
> +        return memberRepository.save(member);
굳이 반환하는 이유가 있을까요?

2022-02-13 06:46 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/service/SignupService.java
> +            throw new DuplicatedLoginIdException();
하나의 기능으로 보이는데 메소드로 분리하는게 더 좋지않을까요?

2022-02-13 06:46 UTC, jinyoungchoi95 commented on src/test/java/com/project/momo/security/TokenProviderTest.java
> +    }
empty method👀

2022-02-13 06:46 UTC, jinyoungchoi95 commented on src/test/java/com/project/momo/security/TokenProviderTest.java
> +        Assertions.assertThat(diff).isEqualTo(Long.parseLong(tokenValidTimeInSeconds));
두가지의 assertions를 사용하고 계시네요. 두 테스트 모두 에러가 발생한다면 어떤 문제가 발생할까요?

2022-02-17 13:02 UTC, myj4513 commented on src/main/java/com/project/momo/entity/Member.java
> +    public static Member createMember(SignupForm signupForm) {
추후 변경 가능성을 고려하지 않고 코드를 수정했던 것 같습니다.

Entity는 실제 데이터베이스의 테이블과 1대1 매핑이 되고, Dto는 View layer과 통신하며 변경이 발생할 가능성이 높으니 Entity가 Dto에 의존적이 않도록 분리하는 것이 좋겠네요.

리뷰 감사합니다!!^^

2022-02-17 13:02 UTC, myj4513 commented on src/main/java/com/project/momo/security/userdetails/UserDetailsServiceImpl.java
> +    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
앗.. 이 코드에서는 username으로 멤버를 조회했을 때 NPE가 발생하네요.

수정하겠습니다;;

2022-02-17 13:08 UTC, myj4513 commented on src/main/java/com/project/momo/security/filter/LoginAuthenticationFilter.java
> +            UsernamePasswordAuthenticationToken auth = new UsernamePasswordAuthenticationToken(loginForm.getLoginId(), loginForm.getPassword());
리뷰 감사합니다!!
추가적으로 getParameterNames()나 getParameterMap()을 사용하면 form 데이터에 대해서만 처리를 해주는 것 같습니다.
RequestWrapper를 사용하여 스트림을 복사하는 방식을 고려해보고 도입하겠습니다!😉

2022-02-17 13:18 UTC, myj4513 commented on src/main/java/com/project/momo/security/handler/AuthenticationEntryPointImpl.java
> +        }
해당 코드는 애플리케이션의 설계가 잘못되어 클라이언트로 응답이 전달되어 작업이 끝나야 할 요청이 ExceptionTranslationFilter까지 들어오게 된 경우를 대비하는 코드입니다. 이 경우에는 리스폰스가 이미 커밋되었기 때문에 사용자에게 추가적인 응답을 전달할 수 없다고 생각됩니다. 여기서 별도의 예외를 던지면 '/error'로 redirect 되지 않을까요??

2022-02-17 13:21 UTC, myj4513 commented on src/main/java/com/project/momo/security/jwt/TokenProvider.java
> +            Jwts.parserBuilder().setSigningKey(key).build().parseClaimsJws(jwt);
미처 생각 못했습니다!! 재사용하겠습니다ㅜㅜ

2022-02-17 13:26 UTC, myj4513 commented on src/main/java/com/project/momo/controller/SignupController.java
> +@RequestMapping("/api/signup")
`/api/login` 처럼 사용자에 대한 회원가입을 단순한 구조의 URI로 사용하려고 하였는데, 리뷰를 보고 생각해보니 명확하지 못한것 같습니다. 수정하겠습니다!!

2022-02-17 13:38 UTC, myj4513 commented on src/main/java/com/project/momo/controller/SignupController.java
> +    }
Controller이 가져야하는 책임의 범위에 대해서 충분히 고려하지 못한것 같습니다.

Service 내부에서 발생한 예외를 Controller로 던진 후 Controller에서 예외를 처리하는 프로세스는 확실히 문제가 있습니다. 그렇다면 Service에서 발생한 예외는 Service 단에서 핸들링 한 후 결과를 Controller로 보내야 합니다. 
위 코드에서 `DuplicatedLoginIdException`의 핸들링 결과는 '로그인 아이디의 중복'을 나타내는 메시지라고 생각됩니다.

만약 `SignupService.signup()`이 String 타입을 반환하게 된다면 Controller에서는 `signup()`에 대한 결과를 널 체크하게 되는데 이러한 코드도 문제가 있다고 생각합니다.

혹시 더 좋은 방법이 있을까요??

2022-02-17 13:50 UTC, myj4513 commented on src/main/java/com/project/momo/dto/signup/SignupForm.java
> +    @NotBlank
테스트 해본 결과 " "(공백)인 경우에는 두가지 예외가 모두 발생하며, `BindingResult`를 스트림을 이용하여 `Map`으로 변환할 경우 `stream.Collectors.duplicateKeyException`이 발생합니다. `@NotBlank`를 `@NotEmpty`로 변경하여 Validation의 중복을 해소하겠습니다.

디테일한 리뷰 감사합니다😍😍😍

2022-02-17 13:50 UTC, Lob-dev commented on src/main/java/com/project/momo/controller/SignupController.java
> +    }
개인적으로는 SignupService가 `DuplicatedLoginIdException` 을 Handling 해야 할 필요가 있는지 의구심이 들어요~  이 로직이 실패하였다고 다시 시도할 만한 성향의 문제가 아니고, 정책에 따라 중단되었음을 사용자에게 안내만 해주면 되는 것으로 보이거든요!

서비스의 요청이 성공했다면 해당 Transaction이 종료되지 않을 것이기 때문에 그대로 진행하고 끝났을 때 성공했다 라는 의미를 가지는 상태 코드를 응답해주면 되지 않을까요?

2022-02-17 13:57 UTC, myj4513 commented on src/main/java/com/project/momo/security/filter/JwtFilter.java
> +public class JwtFilter extends GenericFilterBean {
가장 큰 차이점은 `OncePerRequestFilter`는 `ServletRequest` 당 1회만 실행을 보장한다는 점입니다.
Controller에서 요청을 리다이렉트하는 경우에 `OncePerRequestFilter`를 확장한 필터는 실행 되지 않기 때문에 불필요한 반복을 줄일 수 있습니다.

추가적으로 `GenericFilterBean`은 `Filter`를 확장한 스프링에서 제공하는 추상 클래스로 스프링의 설정정보를 가져올 수 있습니다.

리뷰 감사합니다. 필터에 대해 공부해보는 계기가 되었습니다!

2022-02-17 14:45 UTC, myj4513 commented
## Motivations
- 커멘트를 보고 현재 토큰 인증 방식에 대한 여러 문제점에 대해 고민해보게 되었습니다.
- 여러 필터들과 컨트롤러에 분포되어있는 `response` 처리 방식이 일관적이지 않고 직관적이지 못하다고 생각되었습니다.
<br>

## Key Changes
- 기존 JWT 인증 방식을 `access token`과 `refresh token`을 분리하는 방식으로 변경하여 보안을 강화하였습니다.
- `refresh token`을 DB에 저장하여 토큰조작에도 대처할 수 있도록 설계하였습니다.(완벽한 무상태성은 포기해야합니다..)
- 클라이언트에게 토큰 인증에 대한 다양한 결과를 제공하기 위해 토큰 관련 response를 `AuthEntryPoint`가 아닌 `JwtExceptionFilter`가 전달하도록 설계하였습니다.
- `ResponseManager`가 일관된 방식으로 예외를 처리하도록 설계하였습니다.
  - 모든 예외를 반환할 때, `ResponseManager.sendError()`을 호출합니다.
  - 예외에 따른 별도의 로직 처리는 `JsonConverter`에서 수행됩니다.
  - `JsonConverter`는 `ObjectMapper`를 주입 받아야 하기 때문에 빈으로 등록됩니다.
  - `ResponseManager` 또한 `JsonConverter`를 주입 받으므로 빈으로 등록되지만 여러 컨트롤러와 필터에서 의존성을 줄이기 위해 `@PostConstruct`를 사용하여 static 한 `JsonConverter`를 사용하도록 하였습니다.
- `Request`가 `Body`를 읽을 때 내용이 소모되는 문제를 커스텀한 `RequestWrapper`로 해결하였습니다.
- 클라이언트에 예외를 반환하는 경우 `ExceptionResponseDto` 또는 `ExceptionResponseDto`를 상속하는 클래스를 사용합니다.
<br>

## To Reviewers
- 이번 커멘트들을 보고 여러 디테일들을 놓치고 개발을 하고 있다는 것을 느꼈습니다. 신경쓰며 코딩하겠습니다!!
- Spring Security가 커스터마이징에 관대한 것 같으면서도 제한적인 부분도 많이 존재한다는 것을 느끼게 된것 같습니다.
- 클라이언트에게 리스폰스를 전달하는 부분에 대해 여러번 설계를 하며 작성했습니다.(이부분에 대한 집중적인 리뷰 부탁드립니다.)
- 리뷰 남겨주셔서 정말 감사합니다!!

2022-02-17 14:46 UTC, yyy9942 commented on src/main/java/com/project/momo/security/filter/JwtFilter.java
> +        }
만료된 토큰을 보냈을때랑 잘못된 토큰을 보냈을 때, 모두 같은 케이스로 처리해도 무방할것으로 보이나 협업을 관점으로 생각한다면 각각 다른 상태코드를 내려주는것도 고려해보세요 :)
잘못된 토큰이나 요청은 400 BAD REQUEST
만료된 토큰이나 요청의 경우 401 UNAUTHORIZED를 고려해보면 좋을거같네요. 에러메세지를 내려주어도 좋을거같고요

2022-02-19 12:58 UTC, yyy9942 requested changes
Exception에 대한 ResponseDto를 만드는 방법은 나쁘지 않아보여요.
단지 Exception을 Dto로 바꿔주기위한 컨버팅작업을 할 수 있는 공용 어댑터가 필요할거같기도 하고, 아니면 ExceptionResponseDto의 생성자로 Exception을 받아 알아서 생성할 수 있게해줘도 될거같네요. 안그러면 ExceptonResponseDto를 만드는 방식이나 메세징에 대한 관심사라 여기저기 흩어질 수 있을거같습니다.

테스트코드가 점점 구체화되는거같아서 보기 좋네요!

리뷰중 반영안된것들이 보입니다. 이부분도 반영해주세요

2022-02-19 12:58 UTC, yyy9942 commented on src/main/java/com/project/momo/service/LogoutService.java
> +        } catch (EmptyResultDataAccessException e) {}
catch문에 빈 바디를 두는건 최대한 지양해야합니다. 최소한 로그라도 찍어야하며 명시적인 처리를 해주셔야해요. 안그러면 여기서 에러가 나도 에러가 났는지 알 수 없게되고 Transaction도 롤백이 안됩니다.

2022-02-19 12:58 UTC, yyy9942 commented on src/main/java/com/project/momo/utils/JwtUtils.java
> +    public static final String MEMBER_ID_CLAIM_NAME = "memberId";
유틸 내부에 상수를 두고 이를 외부에서 사용할 수 있도록 public으로 두는게 유틸의 책임을 벗어나는 행위로 보입니다. 공통적으로 여러 클래스에서 사용하는 상수는 명시적인 상수 클래스(또는 Enum)에 담겨있어야 할거같네요.

2022-02-19 12:58 UTC, yyy9942 commented on src/main/java/com/project/momo/utils/JwtUtils.java
> +        return null;
토큰이 유효하지 않으면 앞단에서 Exception을 던지는거같던데요, 여기서도 토큰이 이상하면 예외처리를 해야하지 않을까요?

2022-02-19 12:58 UTC, yyy9942 commented on src/main/java/com/project/momo/utils/RequestWrapper.java
> +    }
Stream을 복사하는게 아닌 Request를 복사하셨네요 :) 이러면 불필요한부분까지 복사되는게 아닌가 싶지만.. 크게 문제될건 없어보입니다.

2022-02-19 12:58 UTC, yyy9942 commented on src/main/java/com/project/momo/utils/JsonConverter.java
> +    }
코드 자체는 나쁘지 않습니다.
하지만 이게 JsonConverter의 역할은 아닌거같아요.

2022-02-19 12:58 UTC, yyy9942 commented on src/main/java/com/project/momo/utils/ResponseManager.java
> +    private final JsonConverter jsonConverter;
이부분에 대해 할 이야기가 많을거같네요. 미팅때 말씀드리겠습니다

2022-02-19 12:58 UTC, yyy9942 commented on src/test/java/com/project/momo/security/TokenProviderTest.java
> +        System.out.println(decodedPayload);
테스트에서 콘솔에 무언가를 출력하여 직접 확인하는일은 지양해야해요~ 자동화된 테스트를 만들어야하는데 콘솔에 출력한걸 직접 확인해야한다면 자동화된 테스트가 아니겠지요?

2022-02-23 07:19 UTC, myj4513 commented
## 이번 수정의 목적은?
1. 필터의 책임의 범위에 대한 재고려
   - `JwtExceptionFilter`는 `JwtFilter`에서 예외가 발생했을 때 예외를 처리하는 필터지만, 기존 코드에서는 refresh-token 검증 및 재발급까지 진행해 주었습니다.
2. 예외처리 전략 수정
   - 예외 응답을 통일된 DTO로 처리하려 하였으나, 예외 별로 부가적인 데이터를 처리하기 위해 해당 DTO를 상속하는 다양한 DTO가 만들어지며 통일된 응답을 처리하지 못하였습니다.
3. Util 패키지의 역할에 대한 재고려
   - Util 클래스는 상태를 가지면 안되지만 `ResponseManager.java`는 상태를 가지면서 `Utils` 패키지에 존재하였습니다.
<br>

## 주요 수정 사항
1. `JwtFilter`와 `JwtExceptionFilter` 수정
   - `JwtFilter`는 요청헤더에 `refresh-token` 존재 여부에 파악한 후, 존재 한다면 `refresh-token`을 검증한 후 `access-token`을 재발급하고 종료합니다.
   - `refresh-token`이 존재하지 않는다면, `access-token`을 검증한 후, 다음 체인을 호출합니다.
   - 위 두 단계에서 토큰 검증은 `TokenProvider`에서 진행하며 실패 시 커스텀 예외인 `JwtException`을 던집니다.
   - `JwtFilter`는 예외를 그대로 throws 하며 `JwtExceptionFilter`에서 예외를 응답으로 처리합니다.
   - <img width="565" alt="JwtFilterFlow" src="https://user-images.githubusercontent.com/78058268/155274845-1e324c09-3652-4012-b494-92519be6b28b.png">
2. 예외처리 전략 수정
   - 모든 예외 응답은 통일된 `ErrorDto` 클래스를 사용하며, 부가적인 데이터는 적절히 가공해 `String message`로 제공합니다.
   - 별도의 가공이 필요하지 않은 예외들은 ErrorCode(enum)을 통해 제공
3. Util 클래스의 역할에 대한 재고려
   - `JsonConverter` 삭제
   - `ResponseManager` -> `component` 패키지로 이동
   - `JwtUtils`, `AuthUtils` 생성
4. 시큐리티 관련 빈 등록 방법 `@Configuration` -> `@Component` 변경
<br>

## To Reviewers
- 예외 처리 전략을 구상하는 과정이 생각보다 까다로웠으며 아직도 명쾌한 해답이 나온 것 같지 않습니다 ㅜㅜ (이부분에 대한 비판적인 리뷰 열심히 듣겠습니다😭😭😭)

2022-02-27 02:47 UTC, Lob-dev commented on src/main/java/com/project/momo/controller/SignupController.java
> +    @GetMapping("/checkDuplicateLoginId")
(Optional) REST를 조금 더 살려보자면 /api/members/loginid/duplicate 또는 /api/members/loginid/check 이런 식의 URL 설계 방향도 고민 해볼만 할 것 같아요~

2022-02-27 03:01 UTC, yyy9942 approved these changes
지금 이야기한거 수정해서 머지해도좋습니다

2022-02-27 16:15 UTC, merged