Feature/oauth
E-TF/Momo pull request #22
Opened 2022-02-28 12:45 UTC by myj4513

## Motivations
- 간편한 로그인 기능을 제공하기 위해 OAuth 로그인 기능을 개발하고자 하였습니다.
- 기존 로그인 기능을 개발할 때 만든 `SuccessHandler`와 `FailureHandler`를 재사용하여 로그인에 대한 통일된 흐름을 유지하고자 하였습니다.
<br>

## Key Changes
- `IMAGE_URL` 테이블은 `MEMBER`와 `CLUB` 테이블과 관계를 맺고 있었으나 해당 테이블의 데이터가 재사용되지 않으며 불필요한 조인 연산을 발생시키므로 을 삭제하였습니다. 
- 커스텀 `OAuth2UserService` 구현
- 기존 Entity에 `@Column(length = xx)`와 `@Size(max = xx)`의 중복을 제거하였습니다.
<br>

## To Reviewers
- 개발 중 Self Invocation issue를 겪고 공부할 수 있는 계기가 되었습니다^^
- `OAuth2Attributes`, `OAuth2UserServiceImpl` 과 `MemberSerivce`가 이번 개발의 핵심 로직입니다!!😝😝

2022-03-01 03:22 UTC, yyy9942 requested changes

2022-03-01 03:22 UTC, yyy9942 commented on src/main/java/com/project/momo/security/consts/OauthType.java
> +    }
Enum과 String의 equals메서드가 적절할까요? Enum에서 value를 꺼내온 후 그걸로 equals를 하는게 더 명시적일거에요.
이렇게 메서드를 짜면, Enum의 name과 동등을 비교하는건지 value와 동등을 비교하는건지 알기 어렵습니다.

2022-03-01 03:22 UTC, yyy9942 commented on src/main/java/com/project/momo/security/jwt/LoginAuthenticationSuccessHandler.java
> +            memberId = memberRepository.findByOauthTypeAndOauthId(OauthType.get(((OAuth2AuthenticationToken) authentication).getAuthorizedClientRegistrationId()), Long.valueOf(authentication.getName(
이 코드는 NPE에 안전하지 않습니다. OAuth type으로 다른 값이 들어왔을 경우 `OauthType.get` 메서드에서 enum을 찾지 못할경우 null을 반환하는데요 그럴경우에 대한 처리가 필요할거같네요. `OauthType.get`메서드에서 null을 반환하는게 아닌 throw를 하는것도 괜찮을거같고, 여기서 명시적으로 예외처리를 해도 좋을거같습니다.

2022-03-01 03:22 UTC, yyy9942 commented on src/main/java/com/project/momo/security/jwt/LoginAuthenticationSuccessHandler.java
> +            memberId = memberRepository.findByOauthTypeAndOauthId(OauthType.get(((OAuth2AuthenticationToken) authentication).getAuthorizedClientRegistrationId()), Long.valueOf(authentication.getName(
클라이언트에서 올바른 OAuth 타입만 보내준다면 베스트겠지만 서버에서는 어떤 요청이 어떻게 들어올지 예상할 수 없어요. 그래서 발생 가능한 예외를 고민해보아야 합니다. 클라이언트를 믿으면 안됩니다! ㅎㅎ

2022-03-01 03:22 UTC, yyy9942 commented on src/main/java/com/project/momo/security/oauth/OAuth2UserServiceImpl.java
> +        OAuth2UserService<OAuth2UserRequest, OAuth2User> delegateService = new DefaultOAuth2UserService();
delegateService 를 loadUser 메서드 호출시마다 생성해야하는것으로 보이는데, 이유가 있을까요?

2022-03-01 03:22 UTC, yyy9942 commented on src/main/java/com/project/momo/security/oauth/OAuth2UserServiceImpl.java
> +        memberService.saveOrUpdate(oAuthAttributes);
loadUser인데 멤버를 저장하고있습니다. 이 경우 회원가입 이후 github에서 정보가 바뀔경우 이 어플리케이션에서도 변경될 것이고, 사용자는 이게 왜 같이 바뀌는것인지 혼란이 올 수 있어요. 이미 저장된 사용자의 정보는 사용자가 명시적으로 변경하지 않는 한 (설령 OAuth에서 바뀌었다고 해도)바꾸지 않는것이 좋습니다.

2022-03-01 03:22 UTC, yyy9942 commented on src/main/java/com/project/momo/security/oauth/dto/GithubOAuthAttributes.java
> +                StringUtils.hasText(imageUrl)?Optional.of(imageUrl):Optional.empty());
`StringUtils.hasText(imageUrl)?Optional.of(imageUrl):Optional.empty());` 이건 간단하게 이렇게 바꿀 수 있습니다.

`Optional.ofNullable(imageUrl)`

2022-03-01 03:22 UTC, yyy9942 commented on src/main/java/com/project/momo/service/MemberService.java
> +    }
위에도 적어두엇듯이, 멤버가 로그인할때마다 정보가 바뀌는건 명시적이지 않아요. 정확하게 멤버가 변경에 대한 액션이 있을 때 바꾸어주는것이 좋습니다.

2022-03-04 06:10 UTC, myj4513 commented
## 이번 수정의 목적은?
1.  `OAuth2ServiceImpl` 클래스의 역할 재고려
    - `OAuth2Service` 는 `OAuth2LoginAuthenticationProvider`에서 `access-token`을 사용해 리소스 서버로부터 엔드유저의 데이터를 가져오는 역할을 수행해야합니다. 기존에 작성한 `OAuth2ServiceImpl`은 이 역할을 벗어난 Member의 생성과 갱신 기능까지 포함하고 있어 이를 분리하고자 하였습니다.
    
2. `OAuth 로그인`과 `OAuth 회원가입` 분리
    -  `OAuth2LoginAuthenticationFilter`는 OAuth 인증을 마친 사용자가 웹서비스를 이용할 수 있는 권한을 부여(인증)하는 역할만을 수행해야합니다. 기존 코드에서는 권한 부여 뿐만 아니라 DB에 저장된 정보가 없는 경우 새로운 Member를 생성 후 저장하는 역할까지 수행하고 있었습니다.
    
3. 이미지 처리 방식 구현

## 주요 수정 사항
1. `OAuth2ServiceImpl`의 제거
    - `OAuth2Service`는 `loadUser()` 단일 메서드를 가진 함수형 인터페이스입니다. `loadUser()`는 User info 엔트포인트로부터 엔드유저의 정보를 가져와 `OAuth2User` 인스턴스를 반환하는 메서드입니다. 해당 메서드에서 권한 부여나 DB 조회에 대한 역할을 확장하기 적합하지 않으므로 제거하여 `DefaultOAuth2Service`를 사용하도록 하였습니다.
2. `OAuth 로그인`과 `OAuth 회원가입` 분리
    - OAuth 로그인과 OAuth 회원가입을 분리하여도 OAuth 인증과 관련한 작업은 공통으로 처리되어야 합니다.
    - 따라서 `requestRedirect`나 `리소스 서버로부터 User info 가져오기`는 기존 `OAuthFilter` 들을 사용한 공통된 처리를 하도록 하였고, OAuth 로그인과 OAuth 회원가입에 대한 분기처리는 `LoginAuthenticationSuccessHandler`에서 처리하도록 하였습니다.
    - OAuth 데이터로 DB 조회 되는 경우 -> OAuth 로그인 : 기존 로그인과 동일하게 `access-token` 과 `refresh-token` 발급
    - OAuth 데이터로 DB 조회 되지 않는 경우 -> OAuth 회원가입 : OAuth 회원가입만 가능한 임시토큰 발급

3. S3 업로더 구현
## To Reviewers
- 최대한 OAuth 관련 로직들이 기존 로그인 흐름에 영향을 주지 않도록 설계하고자 하였습니다!!😣

2022-03-06 03:01 UTC, yyy9942 requested changes
S3 분리해야하고,
나머지는 리뷰 반영하고 머지해도 되겠습니다

2022-03-22 08:06 UTC, merged