회원 정보 수정 및 결제 수단 등록
E-TF/Momo pull request #25
Opened 2022-04-03 01:47 UTC by myj4513

2022-04-06 22:05 UTC, jinyoungchoi95 reviewed
지나가다 보고 갑니다 :)

2022-04-06 22:05 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/common/annotation/validator/OauthTypeValidator.java
> +
개인적으로는 지우는게 더 낫다라고 생각합니다 :)

2022-04-06 22:05 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/common/annotation/validator/OauthTypeValidator.java
>          }
```suggestion
        return Arrays.stream(OauthType.values())
                .anyMatch(oauthType -> oauthType.getValue().equals(value));
```
으로도 쓸 수 있을 것 같네요.

그리고 해당 로직은 `OauthType.java`에서 관리하는게 올바른 책임이 아닐까요?

2022-04-06 22:05 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/controller/MemberController.java
> +//    @DeleteMapping("/password/{}")
```suggestion
```
혼자 개발하시더라도 주석은 제거하시는것이 좋습니다 :)

2022-04-06 22:05 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/controller/MemberController.java
> +        return ResponseEntity.ok().body(true);
밑에 TODO boolean 타입 반환이 여기인 것 같네요 :)

body에 true를 담는다면 무엇이 true인지 명시해서 json반환하는 게 좋지 않을까요?

그리고 `memberService()`의 내용을 보니 어짜피 check가 되지 않으면 예외가 발생하는데요 그럼 예외가 발생하는건 exception handling하시게 될 거고 여기서는 `ResponseEntity.noContent()`를 반환한다면 true를 반환하는 고민을 하지 않아도 될 것 같네요.

2022-04-06 22:05 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/dto/member/MemberInfoResponse.java
> +
```suggestion
```
👀

2022-04-06 22:05 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/dto/member/MemberInfoResponse.java
> +@NoArgsConstructor
```suggestion
@NoArgsConstructor(AccessLevel.PRIVATE)
```
사용하지 않는다면 private으로 막아두는 것이 좋지 않을까요?

2022-04-06 22:05 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/dto/member/PasswordUpdateRequest.java
> +    @Password
저번에도 봤는데 어노테이션 달아두신건 인상깊네요 :)

2022-04-06 22:05 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/entity/Member.java
> +    }
set보다는 update가 더 명시적이지 않을까요?

2022-04-06 22:05 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/repository/PaymentRepository.java
> +    List<Payment> findByMember(Member member);
위의 `Optional<Member>`에서도 찾는 메소드의 네이밍이 `findBy~`과 같이 진행되는데요.

단일 find와 복수 find에 대해서 명시해두는게 좋지않을까요?

2022-04-06 22:05 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/security/oauth/GithubOAuthAttributes.java
> +
```suggestion
        super(OauthType.GITHUB.getValue(), oAuthId, name, email, imageUrl);
```
의미없는 공백 + sout은 제거해주세요

2022-04-06 22:05 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/service/MemberService.java
> +    private final short MAX_PAYMENT_CNT = 3;
```suggestion
    private static final short MAX_PAYMENT_CNT = 3;
```
상수는 static을 달아서 사용합니다 :)

2022-04-06 22:05 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/service/MemberService.java
> +        Optional<Member> member = memberRepository.findById(AuthUtils.getMemberId());
계속해서 다른 메소드에서도 사용하는거 같은데 공통적인 부분을 줄일 수 있는 방법이 없을까요?

2022-04-06 22:05 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/service/MemberService.java
> +        }
```suggestion
        Member member = memberRepository.findById(AuthUtils.getMemberId())
            .orElseThrow(() -> new RuntimeException("~~));
```
가 조금 더 올바른 Optional 사용법일 것 같네요

2022-04-06 22:05 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/service/MemberService.java
> +        checkPassword(passwordUpdateRequest, member.get().getPassword());
`checkPassword()`라는 password를 검증하는 기능은 결국 도메인의 정보를 사용하는 "비즈니스 로직"이라고 생각하는데요.
비즈니스 로직의 관리 대상은 서비스여야할까요 도메인이어야할까요?

2022-04-06 22:05 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/service/MemberService.java
> +        );
`PaymentRequest`에서 `Payment`로 생성 전환해주는 메소드를 만들어 줄 수 있지 않을까요?
가령 `public Payment toPayment()`와 같은 구조로요 :)

2022-04-06 22:05 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/service/MemberService.java
> +    public MemberInfoResponse updateEmail(String email) {
메소드 순서는 사실 사람마다 다른 컨밴션으로 작성하기는 하는데요.

개인적으로는 클래스를 읽을 때 위에서부터 아래로 내려오면서 일관성 있게 주어져야한다고 생각해요.
근데 update관련된 메소드들이 잘 나오다가 중간에 갑자기 `addPayment`메소드가 있고 다시 update메소드가 보이는데 어떻게 생각하시나요?

2022-04-06 22:05 UTC, jinyoungchoi95 commented on src/main/java/com/project/momo/service/MemberService.java
> +    public void checkPayment() {
얘도 결국 `addPayment()`에서 사용한다면 해당 메소드 밑에 두는게 낫겠네요.

2022-06-13 15:14 UTC, yyy9942 requested changes

2022-06-13 15:14 UTC, yyy9942 commented on src/main/java/com/project/momo/common/exception/ErrorCode.java
> +    NO_MEMBER_FOUND(HttpStatus.BAD_REQUEST, "존재하지 않는 회원입니다."),
MEMBER_NOT_FOUNT는 어떤가요? 일반적으로 어떤 리소스를 찾을 때 존재하지 않는다면 NOT FOUND를 많이 씁니다

2022-06-13 15:14 UTC, yyy9942 commented on src/main/java/com/project/momo/controller/MemberController.java
> +        Member member = memberService.getMemberById();
엔티티가 트랜잭션을 벗어나 컨트롤러레벨까지 내려올 경우 여러 문제점이 발생할 수 있습니다. 이전에 리뷰하며 말씀드린 부분도 있었는데요, 엔티티가 트랜잭션 밖으로 나올 경우
- 트랜잭션에서 제공하는 엔티티의 그래프탐색이 불가능해짐
- 더티체킹이 작동하지 않음
- 엔티티 직렬화시 그래프 탐색으로 인한 불필요한 직렬화
등등 여러 문제가 발생할 수 있으니 컨트롤러레벨에는 엔티티가 나오지 않도록 해주세요

2022-06-13 15:14 UTC, yyy9942 commented on src/main/java/com/project/momo/dto/payment/PaymentResponseList.java
> +public class PaymentResponseList {
PaymentResponseList 는 리스트가 아닌 Object잖아요? 이 클래스의 역할은 PamentList를 저장하는 저장소역할을 하는 것이니 다른 네이밍을 고민해보면 어떨까요?

2022-06-13 15:14 UTC, yyy9942 commented on src/main/java/com/project/momo/dto/signup/SignupRequest.java
> +        return Member.createMember(loginId, passwordEncoder.encode(password), name, email, phoneNumber);
passwordEncoder로 패스워드를 인코딩하는건 비즈니스로직에 해당합니다. 인코딩한 패스워드로 객체를 생성해야 할 것으로 보여요. 서비스레이어에서 패스워드를 생성하여 객체를 생성해주세요 :)

2022-06-13 15:14 UTC, yyy9942 commented on src/main/java/com/project/momo/repository/PaymentRepository.java
> +    void deleteAllByMember(Member member);
명시적인 검색용 DTO를 만들어주는게 좋습니다. 엔티티의 범위가 검색용도까지 확장되는건 엔티티 책임 범위가 너무 넓어지게 되어요

2022-06-13 15:14 UTC, yyy9942 commented on src/main/java/com/project/momo/security/oauth/OAuthAttributes.java
> +    private String oauthType;
요건 왜 String으로 다시 변경되었나요?

2022-06-13 15:14 UTC, yyy9942 commented on src/main/java/com/project/momo/service/MemberService.java
> +    private static final short MAX_PAYMENT_CNT = 3;
소스코드에 MAX_PAYMENT_CNT를 두면 이 값을 바꾸기위해선 배포가 필요합니다. 배포 없이 이 값의 변경이 필요하다면 어떤 방식을 쓸 수 있을까요?

2022-06-18 07:57 UTC, myj4513 commented on src/main/java/com/project/momo/service/MemberService.java
> +    private static final short MAX_PAYMENT_CNT = 3;
배포 없이 값을 변경하는 방법은 외부 설정(property) 파일로 분리하여 `@value`를 통해 해당 값을 사용해야 한다고 생각합니다!

2022-06-18 07:59 UTC, myj4513 commented on src/main/java/com/project/momo/common/exception/ErrorCode.java
> +    NO_MEMBER_FOUND(HttpStatus.BAD_REQUEST, "존재하지 않는 회원입니다."),
명명규칙에 따라 개발하는 습관을 기르겠습니다.

2022-06-18 08:37 UTC, myj4513 commented
## 주요 수정 사항

1. 서비스 레이어 메서드명 수정
    - AuthorizationService
      - 인증된 사용자에게 토큰을 발급해준 후, RefreshToken을 DB에 저장
        - saveRefreshToken() → manageRefreshToken()
      - 액세스토큰이 만료된 경우 DB에 저장된 RefreshToken과 비교하여 검증
        - checkRefreshToken() → validateRefreshToken()

    - MemberService → MyPageService
      - getMemberById → getMember
      - getPaymentById → getPayment
      - getPayment → inquireMyPaymentInfo
      - getPaymentList → inquireAllMyPaymentsInfo
      - updateName → changeMyAccountName
      - updateEmail → changeMyAccountEmail
      - updatePhoneNumber → changeMyAccountPhoneNumber
      - updatePassword → changeMyAccountPassword
      - updatePayment → changeMyAccountPayment
      - addPayment → registerNewPayment
      - deletePayment → removeMyPayment
      - deleteAccount → withdraw
      - 
2. 각 레이어의 책임과 역할에 따른 코드 리팩토링
    - `MemberController`의 `memberInfo()`의 비즈니스 로직을 `MemberService`의 `inquireMyAccountInfo()`로 이동
    - DTO의 비밀번호 인코딩 로직 -> 서비스 레이어로 이동

3. 정적 팩토리 메서드의 장점이 활용되지 못하는 코드들을 생성자로 변경
    - `MemberInfoResponse.createMemberInfoResponse()` -> `new MemberInfoResponse()`
    - `PaymentReponse.createPaymentResponse()` -> `new PaymentResponse()`
    - `PaymentResponseList.createPaymentResponseList()` -> `new PaymentListResponse()`

4. 애플리케이션 운영 중 변경 될 가능성이 있는 값을 외부 설정 파일로 추출

## To Reviewers
- 이번 수정사항의 핵심도 이전과 마찬가지로 각 레이어와 객체들의 역할과 책임이었다고 생각합니다.
- 피드백을 통해 수정하며 어떠한 이유로 해당 레이어나 객체가 해당 책임을 가져야 하는지를 고민하며 개발하도록 노력했습니다.
- 리뷰 정말 감사합니다!!😍😭😝

2022-06-18 08:39 UTC, myj4513 commented on src/main/java/com/project/momo/common/annotation/validator/OauthTypeValidator.java
>          }
네, String 타입으로 들어온 값이 `OauthType`에 포함되는지 검증하는 로직은 `OauthType.java`의 책임이 맞다고 생각합니다. 수정하겠습니다!!

2022-06-18 08:40 UTC, myj4513 commented on src/main/java/com/project/momo/controller/MemberController.java
> +//    @DeleteMapping("/password/{}")
조심하겠습니다..

2022-06-18 08:42 UTC, myj4513 commented on src/main/java/com/project/momo/controller/MemberController.java
> +        return ResponseEntity.ok().body(true);
코드를 다시 확인해보니 말씀하신 대로 check 과정을 거친 후 예외가 발생하므로 해당 컨트롤러에는 성공할 경우에만 응답을 하기 때문에 body에 값을 담을 필요가 없습니다. 수정하겠습니다!

2022-06-18 08:43 UTC, myj4513 commented on src/main/java/com/project/momo/dto/member/MemberInfoResponse.java
> +@NoArgsConstructor
접근 제어에 신경쓰겠습니다ㅜㅜ

2022-06-18 08:43 UTC, myj4513 commented on src/main/java/com/project/momo/repository/PaymentRepository.java
> +    List<Payment> findByMember(Member member);
단수와 복수를 구분하기 위해 `find~` -> `findAll~`로 변경하겠습니다.

2022-06-18 08:44 UTC, myj4513 commented on src/main/java/com/project/momo/security/oauth/GithubOAuthAttributes.java
> +
넵 주의하겠습니다.

2022-06-18 08:44 UTC, myj4513 commented on src/main/java/com/project/momo/service/MemberService.java
> +        Optional<Member> member = memberRepository.findById(AuthUtils.getMemberId());
별도의 메서드로 추출하여 코드의 불필요한 중복을 줄이겠습니다.

2022-06-18 08:46 UTC, myj4513 commented on src/main/java/com/project/momo/service/MemberService.java
> +        }
네 정말 좋은 코드라고 생각합니다. Optional 사용법을 좀 더 공부해야겠다고 느꼈습니다ㅜㅜ

2022-06-18 08:47 UTC, myj4513 commented on src/main/java/com/project/momo/service/MemberService.java
> +        checkPassword(passwordUpdateRequest, member.get().getPassword());
비즈니스 로직의 관리 대상은 서비스여야 한다고 생각합니다.

2022-06-18 08:49 UTC, myj4513 commented on src/main/java/com/project/momo/service/MemberService.java
> +    public MemberInfoResponse updateEmail(String email) {
넵 가독성 높은 코드를 작성하도록 수정하는 것이 맞다고 생각합니다!!

2022-07-09 03:52 UTC, myj4513 commented on src/main/java/com/project/momo/controller/MemberController.java
> +        Member member = memberService.getMemberById();
네! 엔티티를 서비스레이어에서 별도의 DTO로 변환하여 컨트롤러레벨에서 노출되지 않도록 변경하겠습니다.

2022-07-09 03:53 UTC, myj4513 commented on src/main/java/com/project/momo/dto/payment/PaymentResponseList.java
> +public class PaymentResponseList {
`PaymentResponseList` -> `PaymentListResponse`로 변경하겠습니다.

2022-07-09 03:54 UTC, myj4513 commented on src/main/java/com/project/momo/dto/signup/SignupRequest.java
> +        return Member.createMember(loginId, passwordEncoder.encode(password), name, email, phoneNumber);
넵 다시 생각해보니 비즈니스 로직을 DTO에서 수행하고 있었네요. 수정하겠습니다.

2022-07-09 03:58 UTC, myj4513 commented on src/main/java/com/project/momo/repository/PaymentRepository.java
> +    void deleteAllByMember(Member member);
넵 스프링 데이터 JPA의 쿼리 메서드 기능을 사용하여 ```List<Payment> findAllByMemberId(Long id);```로 수정하겠습니다.

2022-07-09 03:58 UTC, myj4513 commented on src/main/java/com/project/momo/security/oauth/OAuthAttributes.java
> +    private String oauthType;
앗 실수로 잘못 변경하였습니다ㅜㅜ 수정했습니다!

2022-07-09 03:59 UTC, myj4513 commented on src/main/java/com/project/momo/service/MemberService.java
> +    private static final short MAX_PAYMENT_CNT = 3;
데이터베이스에 시스템 운영과 관련된 별도의 테이블 생성을 고려해보겠습니다!!

2022-07-11 13:06 UTC, myj4513 commented
## 주요 수정 사항
1. Member 엔티티 변경
    - 동시성 이슈를 고려하여 `paymentCnt` 컬럼 삭제
    - `List<Payment> paymentList` 컬럼 추가를 통한 Payment 엔티티와 Member 엔티티 간 양방향 연관관계 설정
2. MemberService의 조회와 변경 분리
    - 트랜잭션의 최소 범위 적용 가능
    - 조회 전용 메서드는 readOnly로 성능 향상
3. MemberService의 메서드들의 파라미터 타입 수정
    -  `Long memberId` -> `long memberId`(`AuthUtils`이 NOT NULL을 보장)
4. `AuthUtils.getMemberId()` 호출을 서비스에서 컨트롤러로 변경
    - AuthUtils 클래스는 스프링 시큐리티(SecurityContext사용)에 종속적이기 떄문에 최대한 비즈니스 로직을 순수 자바로 작성하기 위해 분리 
5. MemberService에 대한 단위 테스트 및 통합 테스트 작성
6. 스프링 OSIV 종료  


## To Reviewers
- `MemberServiceTest` 와 `MemberServiceSpringBootTest`에 대한 집중적인 리뷰 부탁드립니다!!
- 이번 커밋의 목적은 단순히 MemberService에 대한 단위 테스트 작성이었습니다. 하지만 테스트 코드를 작성하다보니 애플리케이션 코드의 여러 문제점을 발견하게 되었고, 대대적인 리팩토링을 하게 되었습니다.😭😭
- 테스트 코드를 작성하면서 크게 두가지를 신경쓰면서 개발하였습니다.
    - 첫째, 서비스 레이어는 최대한 특정 기술에 종속적이지 않은 순수 자바를 사용하자.
    - 둘째, 테스트 코드를 위해 애플리케이션 코드에서 합의점을 찾지 말자.
- (생각한 것보다 두 원칙을 지키면서 개발하기 쉽지 않았고 특히 여러 DTO의 생성자를 열게되는(?) 문제점들이 있었습니다.)
- 비판적인 리뷰도 언제나 감사합니다!!❤️❤️

2022-07-12 15:42 UTC, yyy9942 approved these changes
고생하셨습니다! 깔끔한 코드네요~

2022-07-12 15:42 UTC, yyy9942 commented on src/test/java/com/project/momo/service/MemberServiceSpringBootTest.java
> +    }
👍아주  좋습니다

2022-07-12 15:42 UTC, yyy9942 commented on src/test/java/com/project/momo/service/MemberServiceSpringBootTest.java
> +    }
요기에 EOL 지켜주세요~

2022-07-12 15:42 UTC, yyy9942 commented on src/test/java/com/project/momo/service/MemberServiceTest.java
> +    }
마지막 라인 빈 라인 삭제해주세요~

2022-07-12 15:42 UTC, yyy9942 commented on src/test/java/com/project/momo/service/MemberServiceTest.java
> +    @DisplayName("DB에 존재하지 않는 Member 의 id를 조회하면, BusinessException 이 발생한다.")
Member가 아니라Payment  같네요

2022-07-13 03:35 UTC, merged