모임 가입 기능
E-TF/Momo pull request #29
Opened 2022-07-16 12:50 UTC by myj4513

## Motivations
-
<br>

## Key Changes
-
<br>

## To Reviewers
-

2022-07-26 09:48 UTC, myj4513 commented
feature/club-create 변경사항 pull 진행

2022-07-27 15:48 UTC, yyy9942 commented
@myj4513 
코드리뷰에 앞서 질문에 대한 답변 먼저 하겠습니다.

**Q1**. 현재 단위 테스트를 작성할 때, ClubService의 경우 다섯 개의 빈과 의존관계를 맺고 있어서 테스트 작성 시 모킹처리가 굉장히 까다롭다고 생각됩니다. 이러한 문제는 제 서비스로직의 잘못된 설계가 원인인가요??
**A.** 여러 의존관계를 가진것 자체는 문제가 아닙니다. 해당 빈이 필요로 하는 의존성이 있다면 주입해주면 되고, 테스트코드를 만들 때에는 아래처럼 주입해주고 테스트하면 됩니다.
```
...
private FooRepository fooRepository;
private BarRepository barRepository;
private MyService myService;

@BeforeAll
void init() {
  this.fooRepository = mock(FooRepository.class);
  this.barRepository= mock(BarRepository.class);
  myService = new MyService(fooRepository, barRepository);
}

@Test
void foo() {
  when(fooRepository.foo()).then(...);
  ...
}
```

**Q2**. 컨트롤러와 서비스 사이에 퍼사드 레이어를 추가하여 서비스 간 의존관계를 제거해주는 방법이 올바른 해결방안일까요??
**A**. 같은 계층의 레이어끼리 의존관계를 설정할 경우 대부분의 경우에는 큰 이슈는 없지만, 순환참조가 생기거나 의존성이 꼬이는 경우가 발생할 수 있습니다. 이러한 점을 문제점으로 인식한다면 퍼사드 패턴을 통해 복잡한 의존성을 제거하고, 계층을 하나 더 만듦으로써 같은 계층의 레이어끼리 서로 의존성을 가지지 않게 풀 수 있습니다.

이 패턴은 디자인 패턴의 일종이고 이러한 패턴을 쓰는게 무조건 옳거나 그르다고 말하기는 어렵습니다. 개발자가 어떤것을 문제라고 인식하는지, 어떻게 해결할지에 따라 선택지로 쓰기에는 유효하겠지만 "무조건 이렇게 해야 맞다" 하는 방식으로 접근하려고 하면 길을 잃을 수 있어요.

해당 패턴을 포함한 여러 개발방식에는 장단점이 있고 이를 적용하는건 개발자가 직접 판단하는겁니다. 장단점을 고려해서 사용여부를 결정해주세요 :)

**Q3**. 이번에 개발한 <모임 가입 기능>은 매우 핵심적인 기능이라고 판단됩니다. 그러나 이 핵심 기능에 대해 단위 테스트로 처리할 수 있는 시나리오가 매우 한정적인 것 같습니다.
```
모임 생성 시 해당 회원은 모임에 대한 관리자 권한을 갖는다.
한 모임의 관리자 회원은 해당 모임에 일반회원 권한으로 재가입 시 예외가 발생한다.
한 회원은 같은 모임에 재가입 시 예외가 발생한다.
```
등 이 있습니다.

위와 같은 테스트들은 통합테스트를 통해서만 구현이 가능하다고 생각됩니다. 이런 문제는 잘못된 테스트의 설계가 원인일까요?ㅜㅜ

**A**. 단위테스트로는 Java 코드와 만들어둔 비즈니스 로직을 테스트할 수 있습니다.
위 로직들도 충분히 단위테스트가 가능합니다. JPA를 쓰며 데이터는 엔티티를 기준으로 저장/수정/조회를 하기 때문에 해당 엔티티를 기준으로 Mocking을 하여 findById 등 메서드를 사용했을 때 정해진 엔티티를 반환하도록 하고, 해당 엔티티에 권한이 정상적으로 세팅되었는지 조회할 수 있습니다.

모임에 두번 가입할 수 없는이슈는 DB와 결합된 이슈라서 단위테스트로는 제한적으로 구현이 가능할듯합니다. 의사코드로 이걸 표현하자면 이렇게 되겠니요
```
void validate중복가입() {
  final boolean 이미가입여부 = 모임원조회(clubId, memberId);
  if (이미가입여부) {
    throw ~~Exception(~~)
  }
}
```
위처럼 메서드를 분리하고, 모임원 조회에 mocking처리를 하고,  해당 메서드를 이용하여 단위테스트를 진행하면 될 것입니다.

테스트가 어렵다면 코드가 정돈되지 않았거나 메서드 분리가 덜된거라고 판단할 수 있는 근거가 될 수 있으니 조금 더 고민을 해보셔도 좋을듯합니다.

2022-07-27 16:03 UTC, yyy9942 requested changes
동시성 이슈를 한번 해결해봅시다 :)

2022-07-27 16:03 UTC, yyy9942 commented on src/main/java/com/project/momo/common/constatnt/ClubRole.java
> +    GENERAL
GENERAL 보다는 MEMBER가 더 명시적인 Role일거같습니다

2022-07-27 16:03 UTC, yyy9942 commented on src/main/java/com/project/momo/common/exception/ErrorCode.java
> +    CONSIST_NOT_FOUND(HttpStatus.NOT_FOUND, "해당 클럽에 가입되어 있지 않습니다.");
한글로는 모임, 영문으로는 club
용어를 통일해주는게 좋습니다
```suggestion
    CONSIST_NOT_FOUND(HttpStatus.NOT_FOUND, "해당 모임에 가입되어 있지 않습니다.");
```

2022-07-27 16:03 UTC, yyy9942 commented on src/main/java/com/project/momo/controller/ClubController.java
> +        long clubId = clubService.registerNewClub(clubRegisterRequest, getCurrentMemberId());
동시성 이슈가 발생할 수 있는 코드로 보이네요.
`clubService.checkMaxClubCreationPerMember(memberId);`과 `clubService.registerNewClub(clubRegisterRequest, getCurrentMemberId());` 사이에 누군가가 insert를 하여 모임원수가 변한다면 최대모임원보다 많이 가입할 수 있을듯합니다. 어떻게 해결할 수 있을까요?

2022-07-27 16:03 UTC, yyy9942 commented on src/main/java/com/project/momo/dto/club/ClubJoinRequest.java
> +}
이 클래스는 해당 클래스를 만들 때 생성자도 없고 setter도 없어서 객체를 만들어 사용할 수 없기 때문에 POJO 원칙에 위배됩니다.
리플랙션을 통해 해당 객체가 만들어지겠지만 해당 클래스도 클래스답게 쓸 수 있게 최소한의 접근제어를 허용해주세요.

2022-07-27 16:03 UTC, yyy9942 commented on src/main/java/com/project/momo/dto/club/ClubJoinRequest.java
> +}
`long clubId;` 접근제어자가 빠져있습니다

2022-07-27 16:03 UTC, yyy9942 commented on src/main/java/com/project/momo/common/constatnt/ClubRole.java
> +    GENERAL
그리고 모임원은 하나의 권한만 가질 수 있는듯한데요, Role의 레벨을 관리해주면 좀 더 편리하게 권한을 관리할 수 있습니다. MEMBER(0), MANAGER(1)의 Role을 가진다면 이렇게도 가능합니다.
```
final hasManagerRole(ClubRole role) {
  return role.getLevel() >= MANAGER.getLevel();
}
```

2022-07-27 16:03 UTC, yyy9942 commented on src/main/java/com/project/momo/service/AuthorizationService.java
> +            return;
👍

2022-07-27 16:03 UTC, yyy9942 commented on src/main/java/com/project/momo/service/ClubService.java
> +    }
이 로직으로 보았을 때에는 ClubMember를 insert하고 바로 리턴하기때문에 단위테스트를 진행하기는 어려운 코드로 보입니다. 이런 코드의 경우 굳이 단위테스트를 하지 않아도 좋습니다. 통합테스트로 해도 될거에요

2022-07-28 04:55 UTC, myj4513 commented
@yyy9942 
친절한 리뷰 정말 감사합니다.
덕분에 테스트 코드 작성 시 발생되는 문제의 원인을 파악하고 메서드 분리와 리팩토링을 함께 고려하게 되었습니다.

위 질문에 대한 답변을 읽으면서 추가적으로 궁금한 부분이 있습니다!!

> Q2. 컨트롤러와 서비스 사이에 퍼사드 레이어를 추가하여 서비스 간 의존관계를 제거해주는 방법이 올바른 해결방안일까요??
> A. 같은 계층의 레이어끼리 의존관계를 설정할 경우 대부분의 경우에는 큰 이슈는 없지만, 순환참조가 생기거나 의존성이 꼬이는 경우가 발생할 수 있습니다. 이러한 점을 문제점으로 인식한다면 퍼사드 패턴을 통해 복잡한 의존성을 제거하고, 계층을 하나 더 만듦으로써 같은 계층의 레이어끼리 서로 의존성을 가지지 않게 풀 수 있습니다.

Q2-1. 위 질문의 답변처럼 퍼사드 패턴은 복잡한 서브 시스템들을 단순화된 상위의 인터페이스를 사용하는 패턴으로 현재 상황에서는 서비스간의 복잡한 의존성 문제와 추후에 발생 가능한 순환 참조를 예방할 수 있습니다. 하지만 위와 같은 이유가 아닌, 더 단순한 단위 테스트를 하기위해(다양한 의존관계의 모킹처리를 회피하기 위해) 퍼사드 패턴을 고려한다면 이것은 잘못된 설계인지 궁금합니다.

2022-07-28 05:03 UTC, myj4513 commented on src/main/java/com/project/momo/common/constatnt/ClubRole.java
> +    GENERAL
👍👍👍👍👍👍
미래에 운영 중 모임에 여러 권한이 추가된다면 위 방식대로 레벨을 관리하는 것이 편할 것 같습니다.
바로 적용하겠습니다!!

2022-07-28 05:03 UTC, myj4513 commented on src/main/java/com/project/momo/common/exception/ErrorCode.java
> +    CONSIST_NOT_FOUND(HttpStatus.NOT_FOUND, "해당 클럽에 가입되어 있지 않습니다.");
넵, 헷갈리지 않도록 통일하고 주의하겠습니다.

2022-07-28 05:06 UTC, yyy9942 commented
@myj4513 
**Q2-1**. 위 질문의 답변처럼 퍼사드 패턴은 복잡한 서브 시스템들을 단순화된 상위의 인터페이스를 사용하는 패턴으로 현재 상황에서는 서비스간의 복잡한 의존성 문제와 추후에 발생 가능한 순환 참조를 예방할 수 있습니다. 하지만 위와 같은 이유가 아닌, 더 단순한 단위 테스트를 하기위해(다양한 의존관계의 모킹처리를 회피하기 위해) 퍼사드 패턴을 고려한다면 이것은 잘못된 설계인지 궁금합니다.
**A**. 테스트코드를 짤 때 있어서 메서드의 분리나 레이어의 분리 없이는 테스트작성이 불가능하다면 그 자체로 이미 특정 외부 리소스나 프레임워크에 강결합되어 종속되어있거나, 메서드 하나가 너무 비대한 신호로 받아들일 수 있습니다. 해당 메서드를 풀어내며 테스트코드가 작성 가능한 상태로 쪼개고 관심사를 분리하는 작업은 단순히 테스트코드를 작성하기 위한 수정이 아닌, 해당 기능에 대한 코드 클리닝과 리팩토링 작업이 됩니다.

DTO에 필요한 접근제어를 주지 않거나 순환참조가 발생 가능한 서비스클래스를 그대로 두는것 또한 프레임워크에 강하게 종속된 코드로 볼 수 있으며, 이러한 방식의 코드는 POJO원칙을 위반할 뿐만 아니라 클린코드 원칙에 위배되는 경우가 많이 생길 수 있습니다. 프레임워크에 종속된 코드가 아닌 java 그 자체로도 동작가능한 유연한 코드를 작성하는것이 좋습니다 :)

2022-07-28 05:29 UTC, myj4513 commented on src/main/java/com/project/momo/controller/ClubController.java
> +        long clubId = clubService.registerNewClub(clubRegisterRequest, getCurrentMemberId());
미처 발견하지 못한 문제점 지적 감사합니다.

제 생각에는 이 문제는 데이터 삽입을 위한 검증과 데이터 삽입이 별도의 트랜잭션에서 동작하기 때문에 발생하는 문제라고 생각합니다. 
따라서 2가지 해결방안을 고려해보았습니다.
1. registerNewClub() 에서 checkMaxClubCreationPerMember()를 호출하여 하나의 트랜잭션으로 처리
2. 두 메서드를 호출하는 컨트롤러의 메서드에 분산락 적용

위 두 방법 모두 장단점을 가지고 있습니다.
1번 방식의 경우 트랜잭션의 범위를 최소화 시키며 서비스 레이어보다 상위 계층에서는 트랜잭션을 사용하지 않습니다. 하지만, 데이터의 분리와 삽입에 대한 분리가 이루어지지 않으며 테스트 코드 작성을 고려해보았을 때 하나의 메서드의 책임이 너무 커지며 단위 테스트 작성이 어려울 수 있습니다.
2번 방식의 경우 1번의 문제점을 해결할 수 있지만 분산락을 적용하는 커넥션의 사용 시간이 길어지므로 사용자의 응답시간 지연이 발생할 수 있습니다. 또한 네임드락을 사용할 경우 네임드락을 클럽에 대해 적용해야 하는데, 본 애플리케이션에 대한 트래픽이 높을 것으로 예상되므로 성능 문제를 충분히 고려해보아야 할 것 같습니다.

2022-07-28 05:35 UTC, myj4513 commented on src/main/java/com/project/momo/dto/club/ClubJoinRequest.java
> +}
이전에도 같은 리뷰를 남겨주셨는데 습관이 생겨서 실수했습니다.
특정 프레임워크나 기술에 종속적이지 않도록 POJO 원칙을 지키며 개발에 신경쓰겠습니다ㅜㅜ

2022-07-28 05:35 UTC, myj4513 commented on src/main/java/com/project/momo/service/AuthorizationService.java
> +            return;
❤️❤️

2022-07-29 04:57 UTC, myj4513 commented on src/main/java/com/project/momo/service/ClubService.java
> +    }
네 통합테스트로 진행하겠습니다^^

2022-07-29 04:58 UTC, merged