분산락 기능 개발
E-TF/Momo pull request #31
Opened 2022-07-19 03:32 UTC by myj4513

## Motivations
-
<br>

## Key Changes
-
<br>

## To Reviewers
-

2022-07-20 12:42 UTC, yyy9942 requested changes
네이밍 컨밴션과 코드 퀄리티가 상당히 좋아지는게 보입니다. 👍 👍 
메서드 네이밍 체크 필요한부분만 수정해주세요~

2022-07-20 12:42 UTC, yyy9942 commented on src/main/java/com/project/momo/aop/DistributedLockAspect.java
> +@Order(1)
```
@Order(1)
```
이건 왜 넣으신건가요?

2022-07-20 12:42 UTC, yyy9942 commented on src/main/java/com/project/momo/aop/DistributedLockAspect.java
> +    private static final Duration DEFAULT_TIMEOUT = Duration.ofSeconds(1);
생각보다 1초는 굉장히 짧을 수 있어요. 슬로우쿼리가 섞이면 1초는 금방 넘을듯 하니 조금 넉넉하게 주셔도 될거같습니다

2022-07-20 12:42 UTC, yyy9942 commented on src/main/java/com/project/momo/aop/DistributedLockAspect.java
> +        }
요것도 좋네요, 스프링 시작시에 한번 쭉 스캔해서 두 어노테이션이 같이 쓰이지 않은 메서드가 있으면 에러를 뱉어주어도 될거같습니다.
어떻게 구현할지 힌트이자 키워드를 드리자면, Spring boot lifecycle event 키워드를 찾아보시면 될겁니다

2022-07-20 12:42 UTC, yyy9942 commented on src/main/java/com/project/momo/common/lock/DistributedLockPrefix.java
> +    }
enum에도 lombok을 적용할 수 있습니다. `@Getter`을 사용하면 요건 없어도 될거같네요

2022-07-20 12:42 UTC, yyy9942 commented on src/main/java/com/project/momo/repository/DistributedLockManagerImpl.java
> +public class DistributedLockManagerImpl implements DistributedLockManager {
추상화레이어를 적용한 부분이 좋네요, 인터페이스의 사용방법을 잘 익힌듯 합니다

2022-07-20 12:42 UTC, yyy9942 commented on src/main/java/com/project/momo/repository/DistributedLockManagerImpl.java
> +    }
요 메서드네임만 바꿔봅시다. `check`라는 메서드명은 이게 어떤 역할을 하는지 명시적이지 않네요

2022-07-20 12:42 UTC, yyy9942 commented on src/main/java/com/project/momo/service/ClubService.java
> +    public void registerNewClub(@LockName long memberId, ClubRegisterDto clubRegisterDto) {
👍

2022-07-27 11:32 UTC, myj4513 commented on src/main/java/com/project/momo/aop/DistributedLockAspect.java
> +@Order(1)
`@Order`를 사용한 이유는 AOP 적용 순서 지정을 통한 트랜잭션의 범위를 지정하기 위함입니다.
자세한 설명을 위해 실패 케이스에 대해 설명해보겠습니다!!

AOP 적용 순서를 지정하지 않아 분산락이 우선적용되어 트랜잭션을 시작한 후에 분산락을 획득하는 경우입니다.

![분산락 실패 케이스@1 5x](https://user-images.githubusercontent.com/78058268/181233122-304f0a7c-a029-418c-a5c8-d94e1afd9fa8.png)
위 그림처럼 두 트랜잭션이 동시에 실행되는 경우, 한 트랜잭션에서 분산락(네임드락)을 획득하게 됩니다(동시에 실행되더라도 네임드락은 한 곳에서만 획득 가능합니다). 분산락을 획득한 트랜잭션은 중복 데이터에 대한 검사를 실행한 후 정상적으로 데이터를 삽입합니다. 데이터를 삽입한 후 분산락을 반납하고 트랜잭션을 종료하게됩니다. 그 후, 대기하던 트랜잭션은 분산락을 획득하고 데이터 중복 검사를 실행하지만 REPEATABLE READ 격리 수준을 사용하기 때문에 다른 트랜잭션을 통해 변경된 데이터를 읽을 수 없게되며 비정상적으로 데이터 중복 검사를 통과하게 되고 결국 중복된 데이터가 삽입되게 됩니다.
<br/>
<br/>
다음은 `@Transactional`이 우선적용되어 분산락을 획득한 후 트랜잭션을 시작하는 경우입니다.

![분산락 성공 케이스@1 5x (2)](https://user-images.githubusercontent.com/78058268/181236335-325967be-f84b-4532-ba73-c22785af5fdb.png)

각 요청은 분산락을 획득하기 전까지 트랜잭션을 시작하지 못하고 대기하게 됩니다. 따라서 두번째로 실행되는 트랜잭션은 우선 실행된 트랜잭션이 커밋 후 종료된 시점에 시작하기 때문에 첫번째 트랜잭션의 변경사항을 반영하여 중복 데이터 검사를 실행하게 됩니다. 즉, 중복 검사를 통과하지 못하며 데이터를 삽입하지 않고 종료하게 됩니다.

**_결론적으로 트랜잭션이 분산락을 얻은 후 시작되는 것을 보장하기 위해 AOP 적용 순서를 지정한 것입니다!_**

2022-07-29 05:00 UTC, myj4513 commented on src/main/java/com/project/momo/aop/DistributedLockAspect.java
> +    private static final Duration DEFAULT_TIMEOUT = Duration.ofSeconds(1);
네 3초로 Duration을 늘리고, 이후에는 운영 중 에러 로그를 통해 적절히 조절해도록 해보겠습니다.

2022-07-29 05:00 UTC, myj4513 commented on src/main/java/com/project/momo/aop/DistributedLockAspect.java
> +        }
네 찾아서 적용해보도록 하겠습니다.
좋은 정보 감사합니당^^

2022-07-29 05:01 UTC, myj4513 commented on src/main/java/com/project/momo/repository/DistributedLockManagerImpl.java
> +public class DistributedLockManagerImpl implements DistributedLockManager {
감사합니다!!😍😍

2022-08-02 16:43 UTC, myj4513 commented
## 주요 수정 사항

1. Spring Boot Life Cycle Event 추가
      - Spring Boot 의 ApplicationStartingEvent를 사용하여 어플리케이션 시작 시점에 @DistributedLock과 @LockName이 동시 적용되었는지 검사합니다.
      - ClassLoader를 사용하여 서비스 패키지 내부에 있는 클래스를 가져옵니다.
      - ApplicationContext를 사용하여 검사하려 하였으나, ApplicationContext에는 프록시가 빈으로 등록되어 메서드에 적용된 AOP 애노테이션이 조회되지 않는 문제가 있었습니다.(이 경우엔 SpringReadyEvent 사용)
      - ApplicationStartingEvent는 ApplicationContext가 생성되기 이전에 실행되기 때문에 @Component를 사용하여 빈등록할 수 었습니다. 따라서 SpringBootApplication에 직접 등록해주었습니다.
      - 실행결과
            <img width="532" alt="image" src="https://user-images.githubusercontent.com/78058268/182427436-14ec4013-6355-4ab4-9259-c335755b9db3.png">

2. ObjectProvider 를 사용한 Self-Invocation Issue 해결
    - 외부 호출을 사용하여 Self-Invocation을 해결하는 방법을 고려했으나, 중첩되는 분산락의 갯수만큼 별도의 클래스를 생성해야하는 문제가 발생했기 때문에 ObjectProvider를 사용하였습니다.

3. ThreadLocalConnectionHolder 구조 개선
    - 분산락이 적용될 때마다 새로운 커넥션을 사용하기 때문에 단일 커넥션의 저장하는 구조에서 커넥션 스택(Stack<Connection>)을 사용하는 구조로 변경하였습니다.

## To Reviewers
- 앞선 PR들과는 다르게 문제를 해결할 수 있는 다양한 방법들을 고려해보고, 근거에 따라 판단하고 문제를 해결하는 과정이 재미있었던 PR이었습니다!!
- 위에서 겪은 이슈들을 블로그에 글로 정리해보았습니다!! 미숙한 글이지만 읽어봐주시면 감사하겠습니다!!😍😍
- 블로그 : https://yejun-the-developer.tistory.com/14

2022-08-03 07:15 UTC, yyy9942 commented on src/main/java/com/project/momo/aop/DistributedLockAspect.java
> +@Order(1)
오 좋습니다. 그렇다면 `@Order`에 1과같은 매직넘버를 넣지 말고 별도 이름을 지어준 상수형태로 넣어주세요.

2022-08-03 13:45 UTC, yyy9942 commented on src/main/java/com/project/momo/common/lock/ThreadLocalConnectionHolder.java
> +        connectionHolder.set(stack);
👍

2022-08-03 13:45 UTC, yyy9942 commented on src/main/java/com/project/momo/controller/ClubController.java
> +        return ResponseEntity.ok(fClubService.inquireClubSimpleInfo(clubId));
이건 하나의 트랜잭션으로 묶여야 하는 작업 아닌가요?

2022-08-03 13:45 UTC, yyy9942 commented on src/main/java/com/project/momo/event/LockNameVerifyEvent.java
> +            "Error : @LockName Not Found";
👍

2022-08-03 13:45 UTC, yyy9942 commented on src/main/java/com/project/momo/event/LockNameVerifyEvent.java
> +                    return null;
```suggestion
                    throw Error;
```

2022-08-03 13:45 UTC, yyy9942 commented on src/main/java/com/project/momo/event/LockNameVerifyEvent.java
> +                        for (Annotation annotation : annotations) {
```
collect
  .stream()
  .map(Class:getDeclaredMethods)
  .flatMap(Collection::srteam)
...
  
```
이렇게 풀어서 최대한 가독성좀.. 만들어주세요

2022-08-03 13:45 UTC, yyy9942 commented on src/main/java/com/project/momo/event/LockNameVerifyEvent.java
> +                        System.exit(-1);
-1 같은 매직넘버는 상수화해주세요

2022-08-03 13:45 UTC, yyy9942 commented on src/main/java/com/project/momo/service/SignupService.java
> +    public void signup(@LockName final String loginId, SignupRequest signupRequest) throws BusinessException {
런타임에러인 `throws BusinessException`은 제거해도 될거같습니다

2022-08-04 13:38 UTC, myj4513 commented on src/main/java/com/project/momo/controller/ClubController.java
> +        return ResponseEntity.ok(fClubService.inquireClubSimpleInfo(clubId));
앗.. 네 하나의 트랜잭션으로 묶여야 하는게 맞습니다.
회원이 모임을 생성한 후, 해당 모임에 관리자 권한으로 가입하는 과정에서 실패해서 롤백된다면 모임생성까지 모두 롤백되어야하기 때문입니다.
꼼꼼히 확인해보지 못했네요. 즉시 수정하겠습니다!

2022-08-04 16:03 UTC, myj4513 commented
## 주요 수정 사항

1. LockNameVerityEvent.class 
    - Stream과 메서드 분리를 사용한 리팩토링(가독성 개선)
    - 기존 LockName 미적용 메서드 발견 시 바로 비정상 종료되는 로직을 모든 메서드를 검사하고 종료하도록 개선
    - 실행 결과 
      <img width="605" alt="image" src="https://user-images.githubusercontent.com/78058268/182894051-3099629e-6870-4007-89d6-4d2eb367e8bd.png">
2. Magic Number 제거
3. ClubController.class 에서 모임 생성 시 별도의 트랜잭션에서 모임 가입이 진행되는 기능 수정

2022-08-09 12:27 UTC, yyy9942 approved these changes
확인하였습니다. 고생하셨어요

2022-08-09 14:21 UTC, merged